import { buildArmchair, buildBed, buildBench, buildBlackboard, buildBookshelf, buildBunkBed, buildCafeChair, buildCafeTable, buildChest, buildCoffeeTable, buildConsoleTable, buildDesk, buildDeskLamp, buildDiningChair, buildDiningTable, buildDresser, buildFloorLamp, buildGlassCabinet, buildHangerRack, buildKotatsu, buildLoungeChair, buildMonitor, buildOfficeChair, buildOttoman, buildPendantLamp, buildPiano, buildRoundCoffeeTable, buildRoundRug, buildRoundTableSm, buildRug, buildSchoolDesk, buildSideTable, buildSofa3, buildSofaL, buildStackingChair, buildStool, buildTV, buildTVBoard, buildTableLamp, buildUpholsteredChair, buildWallArt, buildWallClock, buildWardrobe, buildWindsorChair, buildZabuton } from './builders/furniture.js';
import { buildBathSet, buildBathtub, buildCloset, buildCupboard, buildDishwasher, buildEspressoMachine, buildFridge, buildGasStove, buildHandBasin, buildKitchenCounter, buildLockerUnit, buildMicrowave, buildRiceCooker, buildShoeCabinet, buildToilet, buildVanity, buildVendingMachine, buildWallAC, buildWallTV, buildWasher } from './builders/household.js';
import { buildAlumCoilSide, buildAluminumCoil, buildBandedAlumCoil, buildCNCMachine, buildCNCMachiningCenter, buildControlPanel, buildConveyor, buildDrum, buildExportAlumCoil, buildFireExtinguisher, buildForklift, buildIndustrialFurnace, buildIndustrialRobot, buildIndustrialRobotLg, buildInjectionMolder, buildJibCrane, buildLargeHydraulicPress, buildPackagedAlumCoil, buildPalletRack, buildResinPallet, buildScrapBucket, buildSteelPallet, buildTensileTestMachine, buildToolCabinet, buildWoodPallet, buildWorkbench, buildWorker } from './builders/industrial.js';
import { buildHPLC, buildIncubator, buildLabOven, buildSpectrophotometer, buildUltrasonicCleaner, buildVacuumPump } from './builders/instruments.js';
import { build3DPrinter, buildAnalyticalBalance, buildBandSaw, buildBenchGrinder, buildCentrifuge, buildChemShelf, buildDrillPress, buildFumeHood, buildGlassware, buildHydraulicPress, buildLabBench, buildLaserCutter, buildLathe, buildMicroscope, buildMillingMachine, buildOscilloscope, buildScrollSaw, buildTestBench, buildToolRack, buildWelderStation } from './builders/lab.js';
import { buildATM, buildBarCounter, buildBarStool, buildConferenceTable, buildCopier, buildDisplayCase, buildFilingCabinet, buildInfoPanel, buildPedestal, buildProjector, buildProjectorScreen, buildReceptionCounter, buildRegisterCounter, buildRoundTable, buildShelfRack, buildShowcaseFridge, buildWhiteboard } from './builders/office.js';
import { buildBamboo, buildBenjamin, buildCactus, buildDracaena, buildFicusUmbellata, buildMonstera, buildOlive, buildPlant, buildPothos, buildRhapis, buildSansevieria, buildStrelitzia, buildSucculent, buildZZPlant } from './builders/plants.js';
import { buildCampChair, buildCampfire, buildCoolerBox, buildLantern, buildTent } from './builders/outdoor.js';

const FURNITURE_DEFS = [
  { id:'sofa3',   cat:'seating', name:'3人掛けソファ',     icon:'fa-couch',          w:2.2, d:0.95, h:0.85, colorIdx:0, build:buildSofa3 },
  { id:'sofa1',   cat:'seating', name:'1人掛けソファ',     icon:'fa-chair',          w:0.9, d:0.85, h:0.85, colorIdx:0, build:buildArmchair },
  { id:'dchr',    cat:'seating', name:'ダイニングチェア',  icon:'fa-chair',          w:0.48,d:0.48, h:0.9,  colorIdx:2, build:buildDiningChair },
  { id:'ochr',    cat:'seating', name:'オフィスチェア',    icon:'fa-person-sitting', w:0.6, d:0.6,  h:1.1,  colorIdx:2, build:buildOfficeChair },
  { id:'dtable',  cat:'table',   name:'ダイニングテーブル',icon:'fa-table',          w:1.8, d:0.9,  h:0.75, colorIdx:8, build:buildDiningTable },
  { id:'ctable',  cat:'table',   name:'コーヒーテーブル',  icon:'fa-table',          w:1.2, d:0.6,  h:0.42, colorIdx:0, build:buildCoffeeTable },
  { id:'desk',    cat:'table',   name:'デスク',            icon:'fa-desktop',        w:1.4, d:0.7,  h:0.75, colorIdx:1, build:buildDesk },
  { id:'stable',  cat:'table',   name:'サイドテーブル',    icon:'fa-circle-dot',     w:0.5, d:0.5,  h:0.55, colorIdx:1, build:buildSideTable },
  { id:'sbed',    cat:'sleep',   name:'シングルベッド',    icon:'fa-bed',            w:1.0, d:2.1,  h:0.55, colorIdx:1, build:(o)=>buildBed({...o,double:false}) },
  { id:'dbed',    cat:'sleep',   name:'ダブルベッド',      icon:'fa-bed',            w:1.8, d:2.1,  h:0.55, colorIdx:1, build:(o)=>buildBed({...o,double:true}) },
  { id:'wardrobe',cat:'storage', name:'ワードローブ',      icon:'fa-door-closed',    w:1.8, d:0.6,  h:2.1,  colorIdx:1, build:buildWardrobe },
  { id:'shelf',   cat:'storage', name:'本棚',              icon:'fa-book-open',      w:1.0, d:0.3,  h:1.8,  colorIdx:0, build:buildBookshelf },
  { id:'chest',   cat:'storage', name:'チェスト',          icon:'fa-box',            w:1.0, d:0.5,  h:1.0,  colorIdx:2, build:buildChest },
  { id:'tvboard', cat:'storage', name:'テレビボード',      icon:'fa-tv',             w:1.8, d:0.45, h:0.5,  colorIdx:2, build:buildTVBoard },
  { id:'lamp',    cat:'deco',    name:'フロアランプ',      icon:'fa-lightbulb',      w:0.3, d:0.3,  h:1.7,  colorIdx:7, build:buildFloorLamp },
  { id:'plant',   cat:'deco',    name:'観葉植物',          icon:'fa-leaf',           w:0.4, d:0.4,  h:1.3,  colorIdx:5, build:buildPlant, stack:true },
  { id:'tv',      cat:'deco',    name:'テレビ',            icon:'fa-tv',             w:1.4, d:0.1,  h:0.85, colorIdx:2, build:buildTV, stack:true },
  { id:'rug',     cat:'deco',    name:'ラグ',              icon:'fa-rug',            w:2.0, d:1.5,  h:0.02, colorIdx:9, build:buildRug },
  { id:'workbench',  cat:'factory', name:'作業台',          icon:'fa-screwdriver-wrench', w:1.5,  d:0.75, h:0.9,  colorIdx:2, build:buildWorkbench },
  { id:'toolcab',    cat:'factory', name:'ツールキャビネット', icon:'fa-toolbox',          w:0.7,  d:0.45, h:1.12, colorIdx:3, build:buildToolCabinet },
  { id:'conveyor',   cat:'factory', name:'コンベアベルト',   icon:'fa-arrows-left-right',  w:2.4,  d:0.5,  h:0.82, colorIdx:14, build:buildConveyor },
  { id:'robot',      cat:'factory', name:'産業ロボット',     icon:'fa-robot',              w:0.65, d:0.65, h:1.65, colorIdx:7, build:buildIndustrialRobot },
  { id:'cnc',        cat:'factory', name:'CNC工作機械',      icon:'fa-gear',               w:1.2,  d:1.0,  h:1.54, colorIdx:2, build:buildCNCMachine },
  { id:'palletrack', cat:'factory', name:'パレットラック',   icon:'fa-layer-group',         w:1.7,  d:0.5,  h:2.46, colorIdx:3, build:buildPalletRack },
  { id:'ctrlpanel',  cat:'factory', name:'制御盤',           icon:'fa-sliders',            w:0.8,  d:0.45, h:1.86, colorIdx:2, build:buildControlPanel },
  { id:'shoebox',  cat:'storage',  name:'下駄箱',        icon:'fa-shoe-prints',     w:0.9, d:0.35, h:1.1, colorIdx:1, build:buildShoeCabinet },
  { id:'closet',   cat:'storage',  name:'クローゼット',  icon:'fa-door-closed',     w:1.6, d:0.6,  h:2.2, colorIdx:1, build:buildCloset },
  { id:'cupboard', cat:'kitchen',  name:'食器棚',        icon:'fa-wine-glass',      w:0.9, d:0.45, h:1.9, colorIdx:1, build:buildCupboard },
  { id:'kitchen',  cat:'kitchen',  name:'システムキッチン', icon:'fa-sink',         w:2.4, d:0.65, h:0.9, colorIdx:10, build:buildKitchenCounter },
  { id:'stove',    cat:'kitchen',  name:'ガスコンロ',    icon:'fa-fire-burner',     w:0.6, d:0.55, h:0.85, colorIdx:2, build:buildGasStove },
  { id:'microwave',cat:'kitchen',  name:'電子レンジ',    icon:'fa-square',          w:0.5, d:0.4,  h:0.3, colorIdx:2, build:buildMicrowave, stack:true },
  { id:'ricecook', cat:'kitchen',  name:'炊飯器',        icon:'fa-bowl-rice',       w:0.3, d:0.35, h:0.28, colorIdx:10, build:buildRiceCooker, stack:true },
  { id:'fridge',   cat:'kitchen',  name:'冷蔵庫',        icon:'fa-snowflake',       w:0.7, d:0.7,  h:1.8, colorIdx:10, build:buildFridge },
  { id:'toilet',   cat:'sanitary', name:'トイレ',        icon:'fa-toilet',          w:0.5, d:0.7,  h:0.8, colorIdx:10, build:buildToilet },
  { id:'handbasin',cat:'sanitary', name:'手洗い器',      icon:'fa-faucet',          w:0.4, d:0.3,  h:0.85, colorIdx:10, build:buildHandBasin },
  { id:'vanity',   cat:'sanitary', name:'洗面台',        icon:'fa-pump-soap',       w:0.75,d:0.5,  h:1.85, colorIdx:10, build:buildVanity },
  { id:'washer',   cat:'sanitary', name:'洗濯機',        icon:'fa-soap',            w:0.6, d:0.6,  h:0.9, colorIdx:10, build:buildWasher },
  { id:'bathtub',  cat:'sanitary', name:'浴槽',          icon:'fa-bath',            w:0.8, d:1.6,  h:0.6, colorIdx:4, build:buildBathtub },
  { id:'bathset',  cat:'sanitary', name:'ユニットバス',  icon:'fa-shower',          w:1.6, d:1.6,  h:2.2, colorIdx:10, build:buildBathSet },
  { id:'walltv',   cat:'deco',     name:'壁掛けテレビ',  icon:'fa-tv',              w:1.3, d:0.08, h:0.8, colorIdx:2, build:buildWallTV, wallMount:true },
  { id:'wallac',   cat:'household', name:'壁掛けエアコン',   icon:'fa-wind',         w:0.9, d:0.2,  h:0.28, colorIdx:10, build:buildWallAC,           wallMount:true },
  // ---- office ----
  { id:'conftable',  cat:'office',  name:'会議テーブル',      icon:'fa-table',             w:3.6, d:1.2,  h:0.74, colorIdx:8,  build:buildConferenceTable },
  { id:'whiteboard', cat:'office',  name:'ホワイトボード',    icon:'fa-chalkboard',        w:1.5, d:0.04, h:1.4,  colorIdx:1,  build:buildWhiteboard, wallMount:true },
  { id:'projector',cat:'office',  name:'プロジェクター',    icon:'fa-video',        w:0.3, d:0.25, h:0.12, colorIdx:2,  build:buildProjector,         stack:true },
  { id:'projscreen',cat:'office', name:'プロジェクタースクリーン',icon:'fa-rectangle-xmark', w:1.8, d:0.05, h:1.4, colorIdx:1, build:buildProjectorScreen, wallMount:true },
  { id:'filingcab',  cat:'office',  name:'ファイリングキャビネット', icon:'fa-folder',     w:0.46,d:0.62, h:1.32, colorIdx:10, build:buildFilingCabinet },
  { id:'copier',   cat:'office',  name:'コピー機',          icon:'fa-print',        w:0.62,d:0.56, h:1.08, colorIdx:10, build:buildCopier },
  { id:'reception',  cat:'office',  name:'受付カウンター',    icon:'fa-concierge-bell',    w:2.4, d:0.7,  h:1.1,  colorIdx:1,  build:buildReceptionCounter },
  // ---- museum ----
  { id:'displaycase',cat:'museum',  name:'展示ケース',        icon:'fa-box-open',          w:0.88,d:0.52, h:1.3,  colorIdx:10, build:buildDisplayCase },
  { id:'pedestal',   cat:'museum',  name:'展示台',            icon:'fa-chess-rook',        w:0.5, d:0.5,  h:1.05, colorIdx:1,  build:buildPedestal },
  { id:'infopanel',  cat:'museum',  name:'解説パネル',        icon:'fa-sign-hanging',      w:0.76,d:0.03, h:1.5,  colorIdx:1,  build:buildInfoPanel, wallMount:true },
  // ---- shop ----
  { id:'shelfrack',  cat:'shop',    name:'商品棚',            icon:'fa-shelves',           w:1.2, d:0.5,  h:1.9,  colorIdx:1,  build:buildShelfRack },
  { id:'register',   cat:'shop',    name:'レジカウンター',    icon:'fa-cash-register',     w:1.2, d:0.65, h:0.9,  colorIdx:1,  build:buildRegisterCounter },
  { id:'showcasefridge', cat:'shop',name:'ショーケース冷蔵庫',icon:'fa-temperature-low',   w:1.2, d:0.72, h:2.0,  colorIdx:10, build:buildShowcaseFridge },
  { id:'barcounter', cat:'shop',    name:'バーカウンター',    icon:'fa-martini-glass',     w:2.4, d:0.5,  h:1.1,  colorIdx:8,  build:buildBarCounter },
  { id:'barstool',   cat:'shop',    name:'バースツール',      icon:'fa-chair',             w:0.4, d:0.4,  h:0.85, colorIdx:2,  build:buildBarStool },
  { id:'roundtable', cat:'shop',    name:'丸テーブル',        icon:'fa-circle',            w:0.9, d:0.9,  h:0.74, colorIdx:8,  build:buildRoundTable },
  // ---- seating variants ----
  { id:'sofa2',      cat:'seating', name:'2人掛けソファ',     icon:'fa-couch',             w:1.4, d:0.95, h:0.85, colorIdx:0,  build:(o)=>buildSofa3({...o,seats:2}) },
  { id:'sofalow',    cat:'seating', name:'ローソファ',         icon:'fa-couch',             w:2.2, d:1.0,  h:0.72, colorIdx:0,  build:(o)=>buildSofa3({...o,low:true}) },
  { id:'sofal',      cat:'seating', name:'Lソファ',            icon:'fa-couch',             w:2.4, d:1.6,  h:0.85, colorIdx:0,  build:buildSofaL },
  { id:'stool',      cat:'seating', name:'スツール',           icon:'fa-chair',             w:0.4, d:0.4,  h:0.46, colorIdx:2,  build:buildStool },
  { id:'bench',      cat:'seating', name:'ベンチ',             icon:'fa-minus',             w:1.4, d:0.4,  h:0.45, colorIdx:8,  build:buildBench },
  { id:'loungechair',cat:'seating', name:'ラウンジチェア',    icon:'fa-chair',             w:0.8, d:0.85, h:0.78, colorIdx:0,  build:buildLoungeChair },
  { id:'ottoman',    cat:'seating', name:'オットマン',         icon:'fa-cube',              w:0.6, d:0.6,  h:0.4,  colorIdx:5,  build:buildOttoman },
  // ---- table variants ----
  { id:'consoletab', cat:'table',   name:'コンソールテーブル',icon:'fa-table',             w:1.1, d:0.32, h:0.8,  colorIdx:8,  build:buildConsoleTable },
  { id:'roundctab',  cat:'table',   name:'丸コーヒーテーブル',icon:'fa-circle',            w:0.8, d:0.8,  h:0.42, colorIdx:0,  build:buildRoundCoffeeTable },
  { id:'cafechr',       cat:'seating', name:'カフェチェア',          icon:'fa-chair',    w:0.46, d:0.48, h:0.87, colorIdx:8,  build:buildCafeChair },
  { id:'windsorchair',  cat:'seating', name:'ウィンザーチェア',      icon:'fa-chair',    w:0.48, d:0.48, h:0.95, colorIdx:8,  build:buildWindsorChair },
  { id:'stackchr',      cat:'seating', name:'スタッキングチェア',    icon:'fa-chair',    w:0.46, d:0.5,  h:0.82, colorIdx:10, build:buildStackingChair },
  { id:'upholchr',      cat:'seating', name:'レストランチェア',      icon:'fa-chair',    w:0.52, d:0.54, h:0.92, colorIdx:0,  build:buildUpholsteredChair },
  { id:'cafetable',     cat:'table',   name:'カフェテーブル',        icon:'fa-table',    w:0.65, d:0.65, h:0.74, colorIdx:8,  build:buildCafeTable },
  { id:'roundtablesm',  cat:'table',   name:'丸テーブル小',          icon:'fa-circle',   w:0.7,  d:0.7,  h:0.74, colorIdx:8,  build:buildRoundTableSm },
  // ---- sleep variants ----
  { id:'bunkbed',    cat:'sleep',   name:'二段ベッド',         icon:'fa-bed',               w:1.05,d:2.05, h:1.65, colorIdx:1,  build:buildBunkBed },
  // ---- deco variants ----
  { id:'pendlamp',   cat:'deco',    name:'ペンダントライト',  icon:'fa-lightbulb',         w:0.4, d:0.4,  h:1.2,  colorIdx:0,  build:buildPendantLamp },
  { id:'desklamp',   cat:'deco',    name:'デスクランプ',       icon:'fa-lightbulb',         w:0.3, d:0.3,  h:0.5,  colorIdx:2,  build:buildDeskLamp,   stack:true },
  { id:'tablelamp',  cat:'deco',    name:'テーブルランプ',    icon:'fa-lightbulb',         w:0.3, d:0.3,  h:0.55, colorIdx:6,  build:buildTableLamp,  stack:true },
  { id:'cactus',      cat:'deco',    name:'サボテン',           icon:'fa-leaf',     w:0.30, d:0.30, h:0.55,  colorIdx:5,  build:buildCactus,        stack:true },
  { id:'succulent',   cat:'deco',    name:'多肉植物',           icon:'fa-leaf',     w:0.25, d:0.25, h:0.20,  colorIdx:5,  build:buildSucculent,     stack:true },
  // 観葉植物シリーズ
  { id:'monstera',    cat:'deco',    name:'モンステラ',         icon:'fa-leaf',     w:0.80, d:0.80, h:1.65,  colorIdx:5,  build:buildMonstera },
  { id:'dracaena',    cat:'deco',    name:'ドラセナ',           icon:'fa-leaf',     w:0.50, d:0.50, h:1.30,  colorIdx:5,  build:buildDracaena },
  { id:'sansevieria', cat:'deco',    name:'サンスベリア',       icon:'fa-leaf',     w:0.45, d:0.45, h:0.85,  colorIdx:5,  build:buildSansevieria },
  { id:'ficus_umb',   cat:'deco',    name:'フィカス・ウンベラータ',icon:'fa-leaf',  w:0.80, d:0.80, h:1.80,  colorIdx:5,  build:buildFicusUmbellata },
  { id:'rhapis',      cat:'deco',    name:'シュロチク',         icon:'fa-leaf',     w:0.70, d:0.70, h:1.40,  colorIdx:5,  build:buildRhapis },
  { id:'pothos',      cat:'deco',    name:'ポトス',             icon:'fa-leaf',     w:0.40, d:0.40, h:0.35,  colorIdx:5,  build:buildPothos,        stack:true },
  { id:'bamboo',      cat:'deco',    name:'バンブー',           icon:'fa-leaf',     w:0.35, d:0.35, h:0.85,  colorIdx:5,  build:buildBamboo,        stack:true },
  { id:'strelitzia',  cat:'deco',    name:'ストレリチア',       icon:'fa-leaf',     w:0.75, d:0.75, h:1.60,  colorIdx:5,  build:buildStrelitzia },
  { id:'benjamin',    cat:'deco',    name:'ベンジャミン',       icon:'fa-leaf',     w:0.70, d:0.70, h:1.55,  colorIdx:5,  build:buildBenjamin },
  { id:'olive',       cat:'deco',    name:'オリーブ',           icon:'fa-leaf',     w:0.60, d:0.60, h:1.10,  colorIdx:5,  build:buildOlive },
  { id:'zzplant',     cat:'deco',    name:'ZZプラント',         icon:'fa-leaf',     w:0.55, d:0.55, h:1.05,  colorIdx:5,  build:buildZZPlant },
  { id:'roundrug',   cat:'deco',    name:'丸ラグ',             icon:'fa-circle',            w:1.6, d:1.6,  h:0.02, colorIdx:3,  build:buildRoundRug },
  { id:'wallart',    cat:'deco',    name:'ウォールアート',    icon:'fa-image',             w:0.8, d:0.04, h:0.6,  colorIdx:9,  build:buildWallArt,    wallMount:true },
  { id:'wallclock',  cat:'deco',    name:'壁掛け時計',         icon:'fa-clock',             w:0.4, d:0.06, h:0.4,  colorIdx:2,  build:buildWallClock,  wallMount:true },
  // ---- storage variant ----
  { id:'glasscab',   cat:'storage', name:'ガラス棚',           icon:'fa-wine-glass',        w:0.9, d:0.4,  h:1.8,  colorIdx:1,  build:buildGlassCabinet },
  // ---- lab (実験 / 試験 / 加工) ----
  { id:'labbench',   cat:'lab',     name:'実験台',            icon:'fa-flask-vial',        w:2.0,  d:0.75, h:0.85, colorIdx:1,  build:buildLabBench },
  { id:'fumehood',   cat:'lab',     name:'ドラフトチャンバー',icon:'fa-wind',              w:1.4,  d:0.8,  h:2.3,  colorIdx:10, build:buildFumeHood },
  { id:'microscope', cat:'lab',     name:'顕微鏡',            icon:'fa-microscope',        w:0.3,  d:0.4,  h:0.45, colorIdx:2,  build:buildMicroscope, stack:true },
  { id:'centrifuge', cat:'lab',     name:'遠心分離機',        icon:'fa-fan',               w:0.55, d:0.55, h:0.4,  colorIdx:10, build:buildCentrifuge, stack:true },
  { id:'analbalance',cat:'lab',     name:'電子天秤',          icon:'fa-scale-balanced',    w:0.3,  d:0.4,  h:0.32, colorIdx:10, build:buildAnalyticalBalance, stack:true },
  { id:'chemshelf',  cat:'lab',     name:'薬品棚',            icon:'fa-bottle-droplet',    w:1.0,  d:0.4,  h:1.9,  colorIdx:1,  build:buildChemShelf },
  { id:'glassware',  cat:'lab',     name:'実験ガラス器具',    icon:'fa-vial',              w:0.4,  d:0.3,  h:0.32, colorIdx:5,  build:buildGlassware, stack:true },
  { id:'oscilloscope',cat:'lab',    name:'オシロスコープ',    icon:'fa-wave-square',       w:0.42, d:0.4,  h:0.3,  colorIdx:2,  build:buildOscilloscope, stack:true },
  { id:'testbench',  cat:'lab',     name:'測定試験機',        icon:'fa-gauge-high',        w:0.9,  d:0.7,  h:1.6,  colorIdx:2,  build:buildTestBench },
  { id:'lathe',      cat:'lab',     name:'旋盤',              icon:'fa-gears',             w:1.8,  d:0.8,  h:1.35, colorIdx:6,  build:buildLathe },
  { id:'milling',    cat:'lab',     name:'フライス盤',        icon:'fa-screwdriver-wrench',w:1.2,  d:1.1,  h:1.95, colorIdx:6,  build:buildMillingMachine },
  { id:'drillpress', cat:'lab',     name:'ボール盤',          icon:'fa-arrow-down-long',   w:0.6,  d:0.7,  h:1.75, colorIdx:6,  build:buildDrillPress },
  { id:'grinder',    cat:'lab',     name:'グラインダー',      icon:'fa-circle-notch',      w:0.7,  d:0.45, h:1.25, colorIdx:6,  build:buildBenchGrinder },
  { id:'toolrack',   cat:'lab',     name:'工具ラック',        icon:'fa-toolbox',           w:1.0,  d:0.12, h:1.2,  colorIdx:2,  build:buildToolRack, wallMount:true },
  // ---- machining equipment ----
  { id:'bandsaw',    cat:'lab',     name:'帯鋸盤',            icon:'fa-saw',               w:0.6,  d:0.55, h:1.55, colorIdx:6,  build:buildBandSaw },
  { id:'welder',     cat:'lab',     name:'溶接機',            icon:'fa-bolt',              w:0.55, d:0.45, h:0.9,  colorIdx:6,  build:buildWelderStation },
  { id:'hydpress',   cat:'lab',     name:'プレス機',          icon:'fa-arrow-down',        w:0.7,  d:0.65, h:1.8,  colorIdx:6,  build:buildHydraulicPress },
  { id:'printer3d',  cat:'lab',     name:'3Dプリンター',      icon:'fa-cube',              w:0.5,  d:0.5,  h:0.6,  colorIdx:10, build:build3DPrinter,   stack:true },
  { id:'lasercutter',cat:'lab',     name:'レーザーカッター',  icon:'fa-laser-pointer',     w:1.0,  d:0.7,  h:0.35, colorIdx:2,  build:buildLaserCutter },
  { id:'scrollsaw',  cat:'lab',     name:'糸鋸盤',            icon:'fa-scissors',          w:0.55, d:0.45, h:0.95, colorIdx:6,  build:buildScrollSaw },
  // ---- analytical instruments ----
  { id:'hplc',       cat:'lab',     name:'HPLCクロマトグラフ',icon:'fa-chart-line',        w:0.5,  d:0.55, h:1.6,  colorIdx:10, build:buildHPLC },
  { id:'spectropho', cat:'lab',     name:'分光光度計',        icon:'fa-radiation',         w:0.55, d:0.4,  h:0.35, colorIdx:10, build:buildSpectrophotometer, stack:true },
  { id:'laboven',    cat:'lab',     name:'乾燥オーブン',      icon:'fa-fire',              w:0.6,  d:0.5,  h:0.6,  colorIdx:2,  build:buildLabOven },
  { id:'incubator',  cat:'lab',     name:'インキュベーター',  icon:'fa-temperature-half',  w:0.7,  d:0.65, h:0.85, colorIdx:10, build:buildIncubator },
  { id:'ultrasonic', cat:'lab',     name:'超音波洗浄機',      icon:'fa-water',             w:0.35, d:0.28, h:0.28, colorIdx:10, build:buildUltrasonicCleaner, stack:true },
  { id:'vacpump',    cat:'lab',     name:'真空ポンプ',        icon:'fa-pump-soap',         w:0.4,  d:0.3,  h:0.4,  colorIdx:6,  build:buildVacuumPump,  stack:true },
  // ---- factory heavy equipment ----
  { id:'forklift',   cat:'factory', name:'フォークリフト',   icon:'fa-truck-moving',      w:1.45, d:4.0,  h:2.25, colorIdx:12, build:buildForklift },
  { id:'alumcoil',   cat:'factory', name:'アルミコイル',     icon:'fa-circle',            w:1.0,  d:0.8,  h:0.8,  colorIdx:10, build:buildAluminumCoil },
  { id:'scrpbucket', cat:'factory', name:'屑バケット',       icon:'fa-trash',             w:1.0,  d:1.0,  h:0.7,  colorIdx:13, build:buildScrapBucket },
  { id:'tensile',    cat:'lab',     name:'引張試験機',       icon:'fa-arrows-up-down',    w:0.8,  d:0.7,  h:2.0,  colorIdx:10, build:buildTensileTestMachine },
  { id:'woodpallet', cat:'factory', name:'木製パレット',     icon:'fa-pallet',             w:1.1,  d:1.1,  h:0.145, colorIdx:0,  build:buildWoodPallet },
  { id:'steelpallet',cat:'factory', name:'鉄パレット',       icon:'fa-pallet',             w:1.1,  d:1.1,  h:0.15, colorIdx:6,  build:buildSteelPallet },
  { id:'resinpallet',cat:'factory', name:'樹脂パレット',     icon:'fa-pallet',             w:1.1,  d:1.1,  h:0.15, colorIdx:9,  build:buildResinPallet },
  { id:'drum',           cat:'factory', name:'ドラム缶',           icon:'fa-circle',              w:0.58, d:0.58, h:0.88,  colorIdx:9,  build:buildDrum },
  // ---- 大型工業機械 ----
  { id:'cnc_center',     cat:'factory', name:'CNCマシニングセンタ', icon:'fa-gear',                w:3.0,  d:2.2,  h:2.8,   colorIdx:10, build:buildCNCMachiningCenter },
  { id:'ind_robot',      cat:'factory', name:'大型産業ロボット',    icon:'fa-robot',               w:1.2,  d:1.2,  h:2.4,   colorIdx:10, build:buildIndustrialRobotLg },
  { id:'lg_hydpress',    cat:'factory', name:'大型油圧プレス',      icon:'fa-compress-arrows-alt', w:3.2,  d:2.6,  h:5.5,   colorIdx:11, build:buildLargeHydraulicPress },
  { id:'ind_furnace',    cat:'factory', name:'工業炉',              icon:'fa-fire',                w:2.0,  d:1.5,  h:2.2,   colorIdx:2,  build:buildIndustrialFurnace },
  { id:'inj_molder',     cat:'factory', name:'射出成形機',          icon:'fa-cubes',               w:3.5,  d:1.5,  h:2.2,   colorIdx:10, build:buildInjectionMolder },
  // ---- 新規アイテム ----
  { id:'jib_crane',      cat:'factory', name:'ジブクレーン',        icon:'fa-arrow-up-from-bracket', w:2.2,  d:0.5,  h:4.2,   colorIdx:7,  build:buildJibCrane },
  { id:'fire_ext',       cat:'factory', name:'消火器',              icon:'fa-fire-extinguisher',     w:0.2,  d:0.2,  h:0.65,  colorIdx:3,  build:buildFireExtinguisher, stack:true },
  { id:'alumcoil_banded',cat:'factory', name:'バンド掛けアルミコイル',icon:'fa-circle',              w:1.0,  d:0.8,  h:0.8,   colorIdx:10, build:buildBandedAlumCoil },
  { id:'alumcoil_packed', cat:'factory',name:'梱包済みアルミコイル', icon:'fa-box-archive',          w:1.0,  d:0.8,  h:0.8,   colorIdx:1,  build:buildPackagedAlumCoil },
  { id:'alumcoil_export', cat:'factory',name:'輸出梱包アルミコイル', icon:'fa-pallet',               w:1.2,  d:1.2,  h:1.0,   colorIdx:8,  build:buildExportAlumCoil },
  { id:'alumcoil_side',  cat:'factory', name:'横倒しアルミコイル',   icon:'fa-circle',               w:0.8,  d:1.0,  h:0.8,   colorIdx:10, build:buildAlumCoilSide },
  { id:'worker',         cat:'factory', name:'作業員',              icon:'fa-person-walking',        w:0.5,  d:0.5,  h:1.8,   colorIdx:7,  build:buildWorker },
  // ---- 家具追加 ----
  { id:'monitor',       cat:'office',   name:'PCモニター',          icon:'fa-desktop',        w:0.52, d:0.18, h:0.44, colorIdx:2,  build:buildMonitor,         stack:true },
  { id:'kotatsu',       cat:'table',    name:'こたつ',              icon:'fa-table',          w:0.9,  d:0.9,  h:0.38, colorIdx:0,  build:buildKotatsu },
  { id:'dresser',       cat:'storage',  name:'ドレッサー',          icon:'fa-mirror',         w:0.9,  d:0.44, h:1.4,  colorIdx:1,  build:buildDresser },
  { id:'hangerrack',    cat:'storage',  name:'ハンガーラック',      icon:'fa-shirt',          w:1.0,  d:0.4,  h:1.75, colorIdx:7,  build:buildHangerRack },
  { id:'piano',         cat:'deco',     name:'アップライトピアノ',  icon:'fa-music',          w:1.45, d:0.6,  h:1.22, colorIdx:2,  build:buildPiano },
  { id:'espresso',      cat:'kitchen',  name:'エスプレッソマシン',  icon:'fa-mug-hot',        w:0.3,  d:0.38, h:0.42, colorIdx:7,  build:buildEspressoMachine, stack:true },
  { id:'dishwasher',    cat:'kitchen',  name:'食洗機',              icon:'fa-soap',           w:0.6,  d:0.6,  h:0.85, colorIdx:10, build:buildDishwasher },
  { id:'locker',        cat:'storage',  name:'ロッカー',            icon:'fa-lock',           w:1.2,  d:0.45, h:1.85, colorIdx:6,  build:buildLockerUnit },
  { id:'vendingmachine',cat:'shop',     name:'自動販売機',          icon:'fa-coins',          w:0.75, d:0.35, h:1.85, colorIdx:3,  build:buildVendingMachine },
  { id:'atm',           cat:'shop',     name:'ATM',                 icon:'fa-landmark',       w:0.65, d:0.55, h:1.7,  colorIdx:2,  build:buildATM },
  // ---- 学校 ----
  { id:'schooldesk',  cat:'school',   name:'学習机',              icon:'fa-pen-ruler',      w:0.65, d:0.45, h:0.72, colorIdx:0,  build:buildSchoolDesk },
  { id:'blackboard',  cat:'school',   name:'黒板',                icon:'fa-chalkboard',     w:3.0,  d:0.06, h:1.2,  colorIdx:14, build:buildBlackboard, wallMount:true },
  // ---- 和室 ----
  { id:'zabuton',     cat:'seating',  name:'座布団',              icon:'fa-square',         w:0.55, d:0.55, h:0.08, colorIdx:6,  build:buildZabuton },
  // ---- アウトドア ----
  { id:'tent',        cat:'outdoor',  name:'テント',              icon:'fa-tent',           w:2.2,  d:2.4,  h:1.35, colorIdx:5,  build:buildTent },
  { id:'campchair',   cat:'outdoor',  name:'キャンプチェア',      icon:'fa-chair',          w:0.6,  d:0.62, h:0.85, colorIdx:4,  build:buildCampChair },
  { id:'campfire',    cat:'outdoor',  name:'焚き火',              icon:'fa-fire',           w:0.7,  d:0.7,  h:0.45, colorIdx:2,  build:buildCampfire },
  { id:'coolerbox',   cat:'outdoor',  name:'クーラーボックス',    icon:'fa-box-archive',    w:0.6,  d:0.4,  h:0.42, colorIdx:3,  build:buildCoolerBox },
  { id:'lantern',     cat:'outdoor',  name:'ランタン',            icon:'fa-lightbulb',      w:0.18, d:0.18, h:0.32, colorIdx:14, build:buildLantern,   stack:true },
];


export { FURNITURE_DEFS };
