import { buildArmchair, buildBed, buildBench, buildBlackboard, buildBookshelf, buildBunkBed, buildCafeChair, buildCafeTable, buildChest, buildCoffeeTable, buildConsoleTable, buildDesk, buildDeskLamp, buildDiningChair, buildDiningTable, buildDresser, buildFloorLamp, buildGlassCabinet, buildHangerRack, buildKotatsu, buildLoungeChair, buildMonitor, buildOfficeChair, buildOttoman, buildPendantLamp, buildPiano, buildRoundCoffeeTable, buildRoundRug, buildRoundTableSm, buildRug, buildSchoolDesk, buildSideTable, buildSofa3, buildSofaL, buildStackingChair, buildStool, buildTV, buildTVBoard, buildTableLamp, buildUpholsteredChair, buildWallArt, buildWallClock, buildWardrobe, buildWindsorChair, buildZabuton } from './builders/furniture.js';
import { buildBathSet, buildBathtub, buildCloset, buildCupboard, buildDishwasher, buildEspressoMachine, buildFridge, buildGasStove, buildHandBasin, buildKitchenCounter, buildLockerUnit, buildMicrowave, buildRiceCooker, buildShoeCabinet, buildToilet, buildVanity, buildVendingMachine, buildWallAC, buildWallTV, buildWasher } from './builders/household.js';
import { buildAlumCoilSide, buildAluminumCoil, buildBandedAlumCoil, buildCNCMachine, buildCNCMachiningCenter, buildControlPanel, buildConveyor, buildDrum, buildExportAlumCoil, buildFireExtinguisher, buildForklift, buildIndustrialFurnace, buildIndustrialRobot, buildIndustrialRobotLg, buildInjectionMolder, buildJibCrane, buildLargeHydraulicPress, buildPackagedAlumCoil, buildPalletRack, buildResinPallet, buildScrapBucket, buildSteelPallet, buildTensileTestMachine, buildToolCabinet, buildWoodPallet, buildWorkbench, buildWorker } from './builders/industrial.js';
import { buildHPLC, buildIncubator, buildLabOven, buildSpectrophotometer, buildUltrasonicCleaner, buildVacuumPump } from './builders/instruments.js';
import { build3DPrinter, buildAnalyticalBalance, buildBandSaw, buildBenchGrinder, buildCentrifuge, buildChemShelf, buildDrillPress, buildFumeHood, buildGlassware, buildHydraulicPress, buildLabBench, buildLaserCutter, buildLathe, buildMicroscope, buildMillingMachine, buildOscilloscope, buildScrollSaw, buildTestBench, buildToolRack, buildWelderStation } from './builders/lab.js';
import { buildATM, buildBarCounter, buildBarStool, buildBenchDesk, buildBenchDeskDouble, buildConferenceTable, buildCopier, buildDisplayCase, buildFilingCabinet, buildGondolaShelf, buildInfoPanel, buildPedestal, buildProjector, buildProjectorScreen, buildReceptionCounter, buildRegisterCounter, buildRoundTable, buildShelfRack, buildShowcaseFridge, buildWhiteboard } from './builders/office.js';
import { buildRegza55E770S, buildRegza65E770S, buildFjallboTvBench, buildValnasSofa2, buildUgglerumCoffeeTable, buildFagelfjalletBed } from './builders/products.js';

// ---- 実在製品データ (product): 各アイテムのモデルにした製品。mm = 採用した外形寸法, sources = 確認元 ----
const IKEA = (path) => 'https://www.ikea.com/jp/ja/p/' + path;
const PRODUCT = {
  sofa3: { brand:'IKEA', model:'KIVIK 3人掛けソファ（ティッブレビ ベージュ/グレー 594.405.92 ほか）', name:'KIVIK 3人掛けソファ', mm:{ w:2280, d:950, h:830 }, checked:'2026-09-19',
    note:'幅228×奥行95×高さ83cm。座面高45／座面奥行60cm、低めのアームレスト。カバー違いで多数のバリエーション。',
    sources:[ { label:'IKEA公式（日本）KIVIK 3人掛けソファ', url:IKEA('kivik-3-seat-sofa-tibbleby-beige-grey-s59440592/') }, { label:'IKEA公式（日本）KIVIKシリーズ', url:'https://www.ikea.com/jp/ja/cat/kivik-series-18329/' } ] },
  sofa2: { brand:'IKEA', model:'KIVIK 2人掛けソファ（ティッブレビ ベージュ/グレー 194.405.94 ほか）', name:'KIVIK 2人掛けソファ', mm:{ w:1900, d:950, h:830 }, checked:'2026-09-19',
    note:'幅190×奥行95×高さ83cm。3人掛けと同じ奥行・高さで幅のみ短い。',
    sources:[ { label:'IKEA公式（日本）KIVIK 2人掛けソファ', url:IKEA('kivik-2-seat-sofa-tibbleby-beige-grey-s19440594/') } ] },
  sofal: { brand:'IKEA', model:'KIVIK 3人掛けソファ 寝椅子付き（トレースンド ライトベージュ 594.828.41 ほか）', name:'KIVIK 3人掛けソファ 寝椅子付き', mm:{ w:2800, d:1630, h:830 }, checked:'2026-09-19',
    note:'幅280×奥行95cm（寝椅子部は奥行163cm）×高さ83cm。寝椅子は左右どちらにも取付可。奥行(D)は寝椅子部の163cmを採用。',
    sources:[ { label:'IKEA公式（日本）KIVIK 3人掛けソファ 寝椅子付き', url:IKEA('kivik-3-seat-sofa-with-chaise-longue-tresund-light-beige-s59482841/') } ] },
  sofa1: { brand:'IKEA', model:'STRANDMON ウィングチェア（ノールドヴァッラ ダークグレー 303.598.27 ほか）', name:'STRANDMON ウィングチェア', mm:{ w:820, d:960, h:1010 }, checked:'2026-09-19',
    note:'幅82×奥行96×高さ101cm、座面高45cm。1950年代のMKチェアを復刻した高い背もたれのウィングチェア。',
    sources:[ { label:'IKEA公式（日本）STRANDMON ウィングチェア', url:IKEA('strandmon-wing-chair-nordvalla-dark-grey-30359827/') }, { label:'IKEA公式（日本）STRANDMONシリーズ', url:'https://www.ikea.com/jp/ja/cat/strandmon-series-57217/' } ] },
  dchr: { brand:'IKEA', model:'STEFAN チェア ブラウンブラック 803.634.26', name:'STEFAN チェア', mm:{ w:420, d:490, h:900 }, checked:'2026-09-19',
    note:'幅42×奥行49×高さ90cm、座面高45cm。無垢材フレーム、耐荷重110kg。クッション付き（KNISA）のバリエーションあり。',
    sources:[ { label:'IKEA公式（日本）STEFAN チェア', url:IKEA('stefan-chair-brown-black-80363426/') } ] },
  ochr: { brand:'IKEA', model:'MARKUS オフィスチェア（ヴィースレ ダークグレー 502.611.51）', name:'MARKUS オフィスチェア', mm:{ w:620, d:600, h:1290 }, checked:'2026-09-19',
    note:'幅62×奥行60×高さ129〜140cm（最低高を採用）。座面幅53／奥行47cm、座面高46〜57cm、耐荷重110kg。メッシュバック＋一体型ヘッドレスト。',
    sources:[ { label:'IKEA公式（日本）MARKUS オフィスチェア', url:IKEA('markus-office-chair-vissle-dark-grey-50261151/') } ] },
  dtable: { brand:'IKEA', model:'EKEDALEN 伸長式テーブル 180/240×90cm 203.407.63', name:'EKEDALEN 伸長式テーブル', mm:{ w:1800, d:900, h:750 }, checked:'2026-09-19',
    note:'長さ180cm（伸長時240cm）×幅90×高さ75cm。通常時の180cmを採用。4〜6人用。',
    sources:[ { label:'IKEA公式（日本）EKEDALEN 伸長式テーブル', url:IKEA('ekedalen-extendable-table-dark-brown-20340763/') } ] },
  ctable: { brand:'IKEA', model:'LACK コーヒーテーブル 118×78cm 404.499.05', name:'LACK コーヒーテーブル', mm:{ w:1180, d:780, h:450 }, checked:'2026-09-19',
    note:'長さ118×幅78×高さ45cm。天板厚5cm、5×5cmの角脚、下段棚板付き。',
    sources:[ { label:'IKEA公式（日本）LACK コーヒーテーブル', url:IKEA('lack-coffee-table-white-40449899/') } ] },
  desk: { brand:'IKEA', model:'MICKE デスク ホワイト 142×50cm 403.542.78', name:'MICKE デスク', mm:{ w:1420, d:500, h:750 }, checked:'2026-09-19',
    note:'幅142×奥行50×高さ75cm、最大荷重50kg。引き出し1段、背面パネルで配線を隠せる。',
    sources:[ { label:'IKEA公式（日本）MICKE デスク 142x50', url:IKEA('micke-desk-white-40354278/') } ] },
  stable: { brand:'IKEA', model:'LACK サイドテーブル ホワイト 55×55cm 104.499.09', name:'LACK サイドテーブル', mm:{ w:550, d:550, h:450 }, checked:'2026-09-19',
    note:'長さ55×幅55×高さ45cm、最大荷重25kg。',
    sources:[ { label:'IKEA公式（日本）LACK サイドテーブル', url:IKEA('lack-side-table-white-10449909/') } ] },
  sbed: { brand:'IKEA', model:'MALM ベッドフレーム ホワイト 90×200cm 202.651.79', name:'MALM ベッドフレーム シングル', mm:{ w:1050, d:2090, h:1000 }, checked:'2026-09-19',
    note:'外形 長さ209×幅105cm、ヘッドボード高100cm／フットボード高38cm、マットレスサイズ90×200cm（別売）。高さ(H)はヘッドボード高。',
    sources:[ { label:'IKEA公式（日本）MALM ベッドフレーム 90×200', url:IKEA('malm-bed-frame-high-white-20265179/') } ] },
  dbed: { brand:'IKEA', model:'MALM ベッドフレーム ホワイト 140×200cm 302.905.07', name:'MALM ベッドフレーム ダブル', mm:{ w:1560, d:2090, h:1000 }, checked:'2026-09-19',
    note:'外形 長さ209×幅156cm、ヘッドボード高100cm／フットボード高38cm、マットレスサイズ140×200cm（別売）。',
    sources:[ { label:'IKEA公式（日本）MALM ベッドフレーム 140×200', url:IKEA('malm-bed-frame-high-white-30290507/') } ] },
  bunkbed: { brand:'IKEA', model:'MYDAL 2段ベッドフレーム パイン材 90×200cm 003.687.72', name:'MYDAL 2段ベッドフレーム', mm:{ w:970, d:2060, h:1570 }, checked:'2026-09-19',
    note:'幅97×長さ206×高さ157cm。無垢パイン材、耐荷重100kg／段、マットレス厚は最大19cm。',
    sources:[ { label:'IKEA公式（日本）MYDAL 2段ベッドフレーム', url:IKEA('mydal-bunk-bed-frame-pine-00368772/') } ] },
  wardrobe: { brand:'IKEA', model:'PAX ワードローブ ホワイト 150×58×201cm 692.278.74', name:'PAX ワードローブ 150', mm:{ w:1500, d:580, h:2010 }, checked:'2026-09-19',
    note:'幅150×奥行58×高さ201cm。フレーム75cm×2に幅50cmの開き戸3枚（FORSAND）の組み合わせ。',
    sources:[ { label:'IKEA公式（日本）PAX ワードローブ 150x58x201', url:IKEA('pax-wardrobe-white-s69227874/') } ] },
  closet: { brand:'IKEA', model:'PAX / HASVIK ワードローブ 引き戸 ホワイト 200×66×201cm 794.899.26', name:'PAX/HASVIK 引き戸ワードローブ 200', mm:{ w:2000, d:660, h:2010 }, checked:'2026-09-19',
    note:'幅200×奥行66×高さ201cm。引き戸なので開閉スペース不要（造作クローゼットの代替として採用）。',
    sources:[ { label:'IKEA公式（日本）PAX/HASVIK 200x66x201', url:IKEA('pax-hasvik-wardrobe-white-white-s79489926/') } ] },
  shelf: { brand:'IKEA', model:'BILLY 書棚 80×28×202cm 005.220.47', name:'BILLY 書棚', mm:{ w:800, d:280, h:2020 }, checked:'2026-09-19',
    note:'幅80×奥行28×高さ202cm。可動棚4枚＋固定棚1枚で6段。',
    sources:[ { label:'IKEA公式（日本）BILLY 書棚 80x28x202', url:IKEA('billy-bookcase-white-00522047/') } ] },
  chest: { brand:'IKEA', model:'MALM チェスト 引き出し×4 80×100cm 203.546.46', name:'MALM チェスト（引き出し×4）', mm:{ w:800, d:480, h:1000 }, checked:'2026-09-19',
    note:'幅80×奥行48×高さ100cm。取っ手のない前板。壁への固定が必要。',
    sources:[ { label:'IKEA公式（日本）MALM チェスト 引き出し×4', url:IKEA('malm-chest-of-4-drawers-white-20354646/') } ] },
  tvboard: { brand:'IKEA', model:'BESTÅ テレビ台 扉付き ホワイト/ラップヴィーケン 180×42×38cm 192.991.37', name:'BESTÅ テレビ台 180', mm:{ w:1800, d:420, h:380 }, checked:'2026-09-19',
    note:'幅180×奥行42×高さ38cm、テレビ最大荷重30kg。幅60cmの扉3枚。脚を付けると高さ48cm。',
    sources:[ { label:'IKEA公式（日本）BESTÅ テレビ台 180x42x38', url:IKEA('besta-tv-bench-with-doors-white-lappviken-white-s19299137/') } ] },
  shoebox: { brand:'IKEA', model:'HEMNES 靴収納 4コンパートメント ホワイト 107×22×101cm', name:'HEMNES 靴収納', mm:{ w:1070, d:220, h:1010 }, checked:'2026-09-19',
    note:'幅107×奥行22×高さ101cm、靴約8足。前脚のみなので巾木の上に壁付けできる。壁への固定が必要。',
    sources:[ { label:'IKEA公式（日本）HEMNES 靴収納 4コンパートメント', url:IKEA('hemnes-shoe-cabinet-with-4-compartments-white-20161209/') }, { label:'IKEA公式（スウェーデン）寸法 107x22x101', url:'https://www.ikea.com/se/en/p/hemnes-shoe-cabinet-with-4-compartments-white-60156121/' } ] },
  hangerrack: { brand:'IKEA', model:'MULIG 洋服ラック ホワイト 99×46×151cm 801.794.33', name:'MULIG 洋服ラック', mm:{ w:990, d:460, h:1510 }, checked:'2026-09-19',
    note:'幅99×奥行46×高さ151cm。スチール製、ハンガーバー1本＋下段バー。',
    sources:[ { label:'IKEA公式（日本）MULIG 洋服ラック', url:IKEA('mulig-clothes-rack-white-80179433/') } ] },
  dresser: { brand:'IKEA', model:'HEMNES ドレッシングテーブル ミラー付き ホワイト 100×50cm 103.556.70', name:'HEMNES ドレッシングテーブル', mm:{ w:1000, d:500, h:1590 }, checked:'2026-09-19',
    note:'幅100×奥行50×高さ159cm（テーブル高74cm＋ミラー）。無垢材、ガラス天板。',
    sources:[ { label:'IKEA公式（日本）HEMNES ドレッシングテーブル ミラー付き', url:IKEA('hemnes-dressing-table-white-10355670/') } ] },
  cupboard: { brand:'ニトリ', model:'キッチンボード（レジューム 90AG-S DBR/90QH-R DBR）', name:'レジューム キッチンボード 幅90', mm:{ w:900, d:510, h:2010 }, checked:'2026-09-19',
    note:'幅90×奥行51×高さ201cm（上台106cm＋下台95cm）。上台・下台の組み合わせで型番が変わる（扉／引き出し構成は型番により異なる）。',
    sources:[ { label:'ニトリ公式 キッチンボード（レジューム 90AG-S）', url:'https://www.nitori-net.jp/ec/product/4714522-4714582/' } ] },
  kitchen: { brand:'LIXIL', model:'シエラS 壁付I型 基本プラン 間口2400mm 奥行650mm', name:'LIXIL シエラS I型 2400', mm:{ w:2400, d:650, h:850 }, checked:'2026-09-19',
    note:'間口2400×奥行650mm、ワークトップ高85cm（80/85/90cmから選択）。高さ(H)はワークトップ高。吊戸棚は含まない。ステンレストップ、シンク＋ビルトインコンロ。',
    sources:[ { label:'LIXIL公式 シエラS', url:'https://www.lixil.co.jp/lineup/kitchen/shiera/' }, { label:'LIXIL 商品選定カタログ（シエラS I型レイアウト）', url:'https://www2.biz-lixil.com/files/user/contents/proptool_sheet/yok-24002-240403.pdf' } ] },
  stove: { brand:'リンナイ', model:'ガステーブル RT64JH6S2-G（59cm幅・2口・水無し片面焼グリル）', name:'リンナイ RT64JH ガステーブル', mm:{ w:596, d:452, h:218 }, checked:'2026-09-19',
    note:'本体外形 幅596×奥行452×高さ218mm。モデルは汎用コンロ台（幅60×奥行55×高さ約65cm）に載せた状態で、カタログ寸法(W60×D55×H87cm)はその合計。',
    sources:[ { label:'リンナイ公式通販 ガステーブル スタンダード 仕様', url:'https://www.rinnai-basic.jp/gastable/standard/spec/' }, { label:'参考: 楽天市場 RT64JH6S2-G', url:'https://item.rakuten.co.jp/gas/rt64jh6s2-g/' } ] },
  microwave: { brand:'Panasonic', model:'オーブンレンジ NE-MS4C（26L）', name:'Panasonic NE-MS4C', mm:{ w:470, d:390, h:350 }, checked:'2026-09-19',
    note:'外形寸法 幅470×奥行390×高さ350mm、庫内 幅370×奥行335×高さ206mm。',
    sources:[ { label:'Panasonic公式 NE-MS4C 仕様', url:'https://panasonic.jp/range/products/NE-MS4C/spec.html' } ] },
  ricecook: { brand:'象印', model:'極め炊き IH炊飯ジャー NW-VD10（5.5合）', name:'象印 NW-VD10', mm:{ w:255, d:375, h:205 }, checked:'2026-09-19',
    note:'外形寸法 幅25.5×奥行37.5×高さ20.5cm（ふた開き時 約41cm）。',
    sources:[ { label:'象印公式 NW-VD10・18 商品情報', url:'https://www.zojirushi.co.jp/syohin/rice/ricecooker/nw-vd/' } ] },
  fridge: { brand:'Panasonic', model:'冷凍冷蔵庫 NR-C344C（335L・3ドア・右開き）', name:'Panasonic NR-C344C', mm:{ w:590, d:633, h:1687 }, weightKg:66, checked:'2026-09-19',
    note:'外形寸法 幅590×奥行633×高さ1687mm、質量66kg。上から冷蔵室179L／野菜室88L／冷凍室68L。',
    sources:[ { label:'Panasonic公式 NR-C344C', url:'https://panasonic.jp/reizo/products/NR-C344C.html' } ] },
  toilet: { brand:'TOTO', model:'ピュアレストQR 組み合わせ便器 CS232B＋SH232BA（床排水200mm・手洗なし）', name:'TOTO ピュアレストQR', mm:{ w:418, d:760, h:817 }, checked:'2026-09-19',
    note:'手洗なしタンクで横幅418×奥行718×高さ817mm（販売店掲載値）。壁から便器先端までの寸法はTOTO公式で760mmのため、奥行(D)は760mmを採用。便座は別売。',
    sources:[ { label:'TOTO公式 ピュアレストQR', url:'https://jp.toto.com/products/toilet/purerest_qr/' }, { label:'参考: トイレリフォーム専門店（サイズ記載）', url:'https://toirereform.com/toilet/toilet-pyuarest-qr' } ] },
  handbasin: { brand:'TOTO', model:'壁掛手洗器 L870型 LSL870ASR（ハンドル式・壁給水・床排水）', name:'TOTO L870 手洗器', mm:{ w:460, d:205, h:850 }, checked:'2026-09-19',
    note:'手洗器本体 幅460×奥行205mm。高さ(H)は床からの水栓上端の想定値（リム高≒75cmで設置）。',
    sources:[ { label:'参考: サンリフレ TOTO LSL870ASR', url:'https://www.sunrefre.jp/wc/toto/LSL870ASR/' }, { label:'参考: 広瀬トータルサービス LSL870ASR', url:'https://h-totalservice.com/lsl870asr/' } ] },
  vanity: { brand:'LIXIL', model:'洗面化粧台 オフト 間口750（片引出タイプ FTV1H-754 ＋ 1面鏡）', name:'LIXIL オフト 750', mm:{ w:750, d:500, h:1800 }, checked:'2026-09-19',
    note:'間口750×奥行500mm、洗面ボウル高815mm。1面鏡（標準）で全高1800mm（3面鏡は1780/1850mm）。',
    sources:[ { label:'LIXIL公式 オフト', url:'https://www.lixil.co.jp/lineup/powderroom/oft/' }, { label:'参考: サンリフレ オフト 間口750', url:'https://www.sunrefre.jp/powderroom/senmen/inax/oft-width750set/' } ] },
  washer: { brand:'Panasonic', model:'縦型全自動洗濯機 NA-FA8H3（8kg）', name:'Panasonic NA-FA8H3', mm:{ w:564, d:573, h:1022 }, weightKg:34, checked:'2026-09-19',
    note:'外形寸法 幅564×奥行573×高さ1022mm（給・排水ホース含む）、質量約34kg。',
    sources:[ { label:'Panasonic公式 NA-FA8H3 詳細（スペック）', url:'https://panasonic.jp/wash/c-db/products/NA-FA8H3/spec.html' } ] },
  bathtub: { brand:'TOTO', model:'洋風バス ポリバス 1600サイズ P1030R/LN（二方全エプロン）', name:'TOTO ポリバス 1600', mm:{ w:820, d:1640, h:465 }, checked:'2026-09-19',
    note:'長さ1640×幅820×高さ465mm、満水時湯量210L。奥行(D)に長さ1640mmを採用。',
    sources:[ { label:'参考: タカラ住設ショップ TOTO P1030R/LN', url:'https://house.tss-shop.com/products/P1030_N&pri=y' }, { label:'TOTO公式 浴槽（単体浴槽）', url:'https://jp.toto.com/products/bath/' } ] },
  bathset: { brand:'LIXIL', model:'システムバスルーム リノビオV 1616サイズ（マンションリフォーム用）', name:'LIXIL リノビオV 1616', mm:{ w:1600, d:1600, h:2005 }, checked:'2026-09-19',
    note:'内寸 1600×1600mm、天井高2005mm（設置必要寸法 1660×1660×2439mm）。モデルは内寸で表現。',
    sources:[ { label:'LIXIL公式 リノビオV', url:'https://www.lixil.co.jp/lineup/bathroom/renobio/' }, { label:'参考: i-port リノビオV 1616 Mタイプ', url:'https://www.i-port.jp/shopdetail/000000006414/' } ] },
  walltv: { brand:'TVS REGZA', model:'55E770S（55V型 4K Mini LED液晶）壁掛け・スタンドなし', name:'レグザ 55E770S（壁掛け）', mm:{ w:1226, d:77, h:711 }, weightKg:15.4, checked:'2026-09-19',
    note:'スタンドなし外形 幅122.6×高さ71.1×奥行7.7cm、質量15.4kg。壁掛け金具は別売（奥行はモデル上8cm）。',
    sources:[ { label:'REGZA公式 仕様表（E770S）', url:'https://www.regza.com/tv/lineup/e770s/spec' } ] },
  tv: { brand:'TVS REGZA', model:'65E770S（65V型 4K Mini LED液晶）', name:'レグザ 65E770S', mm:{ w:1446, d:316, h:885 }, weightKg:21.0, checked:'2026-09-19',
    note:'スタンド含む外形 幅144.6×高さ88.5×奥行31.6cm、質量21.0kg。テレビ台に載せて使用。',
    sources:[ { label:'REGZA公式 仕様表（E770S）', url:'https://www.regza.com/tv/lineup/e770s/spec' }, { label:'参考: 価格.com 65E770S', url:'https://kakaku.com/item/K0001789866/' } ] },
  wallac: { brand:'ダイキン', model:'ルームエアコン Eシリーズ S224ATES-W（おもに6畳・室内機 F224ATES）', name:'ダイキン Eシリーズ 6畳用 室内機', mm:{ w:798, d:255, h:250 }, checked:'2026-09-19',
    note:'室内機 幅798×高さ250×奥行255mm。室外機（幅675×高さ550×奥行284mm）は含まない。',
    sources:[ { label:'ダイキン公式 Eシリーズ 仕様', url:'https://www.ac.daikin.co.jp/kabekake/2024/products/e_series/spec' } ] },
  lamp: { brand:'IKEA', model:'HEKTAR フロアランプ ダークグレー 402.165.45', name:'HEKTAR フロアランプ', mm:{ w:340, d:340, h:1810 }, checked:'2026-09-19',
    note:'高さ181cm、シェード直径31.5cm、ベース直径34cm。首振りシェード。',
    sources:[ { label:'IKEA公式（日本）HEKTAR フロアランプ', url:IKEA('hektar-floor-lamp-dark-grey-40216545/') } ] },
  pendlamp: { brand:'IKEA', model:'REGOLIT ペンダントランプシェード ホワイト 45cm 001.727.89（＋HEMMA コードセット）', name:'REGOLIT ペンダントランプシェード', mm:{ w:450, d:450, h:1200 }, checked:'2026-09-19',
    note:'和紙製の球形シェード 直径45cm。コードセット・電球は別売。高さ(H)は天井からの吊り下げ範囲の目安。',
    sources:[ { label:'IKEA公式（日本）REGOLIT 45cm', url:IKEA('regolit-pendant-lamp-shade-white-00172789/') } ] },
  rug: { brand:'IKEA', model:'STOENSE ラグ パイル短 オフホワイト 133×195cm 204.270.06', name:'STOENSE ラグ 133×195', mm:{ w:1950, d:1330, h:18 }, checked:'2026-09-19',
    note:'長さ195×幅133cm、パイル短。幅(W)に長さ195cmを採用。',
    sources:[ { label:'IKEA公式（日本）STOENSE ラグ 133x195', url:IKEA('stoense-rug-low-pile-off-white-20427006/') } ] },
  kotatsu: { brand:'東谷（AZUMAYA）', model:'こたつテーブル KT-115（正方形 75cm・アカシア・石英管ヒーター300W）', name:'東谷 KT-115 こたつ', mm:{ w:750, d:750, h:380 }, checked:'2026-09-19',
    note:'幅75×奥行75×高さ38cm、重量13kg。こたつ布団は別売（モデルの布団は表現用）。',
    sources:[ { label:'参考: Yahoo!ショッピング 東谷 KT-115', url:'https://store.shopping.yahoo.co.jp/palette-life/kt-115.html' }, { label:'参考: うさぎ屋 AZM-KT-115', url:'https://store.shopping.yahoo.co.jp/usagi-shop/azm-kt-115.html' } ] },
};
import { buildBamboo, buildBenjamin, buildCactus, buildDracaena, buildFicusUmbellata, buildMonstera, buildOlive, buildPlant, buildPothos, buildRhapis, buildSansevieria, buildStrelitzia, buildSucculent, buildZZPlant } from './builders/plants.js';
import { buildCampChair, buildCampfire, buildCoolerBox, buildLantern, buildTent } from './builders/outdoor.js';
import { buildPerson, buildTeddyBear, buildBunnyPlush, buildUnicornToy, buildBalloon, buildHeartCushion, buildBuildingBlocks, buildToyBox, buildDollhouse, buildCake, buildCupcake, buildKidsBed, buildKidsDesk, buildKidsChair, buildGarland, buildStarWall } from './builders/kawaii.js';

const FURNITURE_DEFS = [
  { id:'sofa3',   cat:'seating', name:'3人掛けソファ',     icon:'fa-couch',          w:2.28,d:0.95, h:0.83, colorIdx:11,build:buildSofa3,     product:PRODUCT.sofa3 },
  { id:'sofa1',   cat:'seating', name:'1人掛けソファ',     icon:'fa-chair',          w:0.82,d:0.96, h:1.01, colorIdx:13,build:buildArmchair,  product:PRODUCT.sofa1 },
  { id:'dchr',    cat:'seating', name:'ダイニングチェア',  icon:'fa-chair',          w:0.42,d:0.49, h:0.9,  colorIdx:2, build:buildDiningChair, product:PRODUCT.dchr },
  { id:'ochr',    cat:'seating', name:'オフィスチェア',    icon:'fa-person-sitting', w:0.62,d:0.6,  h:1.29, colorIdx:2, build:buildOfficeChair, product:PRODUCT.ochr },
  { id:'dtable',  cat:'table',   name:'ダイニングテーブル',icon:'fa-table',          w:1.8, d:0.9,  h:0.75, colorIdx:8, build:buildDiningTable, product:PRODUCT.dtable },
  { id:'ctable',  cat:'table',   name:'コーヒーテーブル',  icon:'fa-table',          w:1.18,d:0.78, h:0.45, colorIdx:1, build:buildCoffeeTable, product:PRODUCT.ctable },
  { id:'desk',    cat:'table',   name:'デスク',            icon:'fa-desktop',        w:1.42,d:0.5,  h:0.75, colorIdx:1, build:buildDesk,        product:PRODUCT.desk },
  { id:'stable',  cat:'table',   name:'サイドテーブル',    icon:'fa-circle-dot',     w:0.55,d:0.55, h:0.45, colorIdx:1, build:buildSideTable,   product:PRODUCT.stable },
  { id:'sbed',    cat:'sleep',   name:'シングルベッド',    icon:'fa-bed',            w:1.05,d:2.09, h:1.0,  colorIdx:4, build:(o)=>buildBed({...o,double:false}), product:PRODUCT.sbed },
  { id:'dbed',    cat:'sleep',   name:'ダブルベッド',      icon:'fa-bed',            w:1.56,d:2.09, h:1.0,  colorIdx:4, build:(o)=>buildBed({...o,double:true}),  product:PRODUCT.dbed },
  { id:'wardrobe',cat:'storage', name:'ワードローブ',      icon:'fa-door-closed',    w:1.5, d:0.58, h:2.01, colorIdx:1, build:buildWardrobe,    product:PRODUCT.wardrobe },
  { id:'shelf',   cat:'storage', name:'本棚',              icon:'fa-book-open',      w:0.8, d:0.28, h:2.02, colorIdx:1, build:buildBookshelf,   product:PRODUCT.shelf },
  { id:'chest',   cat:'storage', name:'チェスト',          icon:'fa-box',            w:0.8, d:0.48, h:1.0,  colorIdx:1, build:buildChest,       product:PRODUCT.chest },
  { id:'tvboard', cat:'storage', name:'テレビボード',      icon:'fa-tv',             w:1.8, d:0.42, h:0.38, colorIdx:1, build:buildTVBoard,     product:PRODUCT.tvboard },
  { id:'lamp',    cat:'deco',    name:'フロアランプ',      icon:'fa-lightbulb',      w:0.34,d:0.34, h:1.81, colorIdx:13,build:buildFloorLamp,   product:PRODUCT.lamp },
  { id:'plant',   cat:'deco',    name:'観葉植物',          icon:'fa-leaf',           w:0.4, d:0.4,  h:1.3,  colorIdx:5, build:buildPlant, stack:true },
  { id:'tv',      cat:'deco',    name:'テレビ（65V型）',   icon:'fa-tv',             w:1.446,d:0.316,h:0.885,colorIdx:13,build:buildRegza65E770S, stack:true, product:PRODUCT.tv },
  { id:'rug',     cat:'deco',    name:'ラグ',              icon:'fa-rug',            w:1.95,d:1.33, h:0.02, colorIdx:10,build:buildRug,         product:PRODUCT.rug },
  { id:'workbench',  cat:'factory', name:'作業台',          icon:'fa-screwdriver-wrench', w:1.5,  d:0.75, h:0.9,  colorIdx:2, build:buildWorkbench },
  { id:'toolcab',    cat:'factory', name:'ツールキャビネット', icon:'fa-toolbox',          w:0.7,  d:0.45, h:1.12, colorIdx:3, build:buildToolCabinet },
  { id:'conveyor',   cat:'factory', name:'コンベアベルト',   icon:'fa-arrows-left-right',  w:2.4,  d:0.5,  h:0.82, colorIdx:14, build:buildConveyor },
  { id:'robot',      cat:'factory', name:'産業ロボット',     icon:'fa-robot',              w:0.65, d:0.65, h:1.65, colorIdx:7, build:buildIndustrialRobot },
  { id:'cnc',        cat:'factory', name:'CNC工作機械',      icon:'fa-gear',               w:1.2,  d:1.0,  h:1.54, colorIdx:2, build:buildCNCMachine },
  { id:'palletrack', cat:'factory', name:'パレットラック',   icon:'fa-layer-group',         w:1.7,  d:0.5,  h:2.46, colorIdx:3, build:buildPalletRack },
  { id:'ctrlpanel',  cat:'factory', name:'制御盤',           icon:'fa-sliders',            w:0.8,  d:0.45, h:1.86, colorIdx:2, build:buildControlPanel },
  { id:'shoebox',  cat:'storage',  name:'下駄箱',        icon:'fa-shoe-prints',     w:1.07,d:0.22, h:1.01, colorIdx:1,  build:buildShoeCabinet,    product:PRODUCT.shoebox },
  { id:'closet',   cat:'storage',  name:'クローゼット',  icon:'fa-door-closed',     w:2.0, d:0.66, h:2.01, colorIdx:1,  build:buildCloset,         product:PRODUCT.closet },
  { id:'cupboard', cat:'kitchen',  name:'食器棚',        icon:'fa-wine-glass',      w:0.9, d:0.51, h:2.01, colorIdx:1,  build:buildCupboard,       product:PRODUCT.cupboard },
  { id:'kitchen',  cat:'kitchen',  name:'システムキッチン', icon:'fa-sink',         w:2.4, d:0.65, h:0.85, colorIdx:10, build:buildKitchenCounter, product:PRODUCT.kitchen },
  { id:'stove',    cat:'kitchen',  name:'ガスコンロ',    icon:'fa-fire-burner',     w:0.6, d:0.55, h:0.87, colorIdx:2,  build:buildGasStove,       product:PRODUCT.stove },
  { id:'microwave',cat:'kitchen',  name:'電子レンジ',    icon:'fa-square',          w:0.47,d:0.39, h:0.35, colorIdx:2,  build:buildMicrowave, stack:true, product:PRODUCT.microwave },
  { id:'ricecook', cat:'kitchen',  name:'炊飯器',        icon:'fa-bowl-rice',       w:0.255,d:0.375,h:0.205,colorIdx:10, build:buildRiceCooker, stack:true, product:PRODUCT.ricecook },
  { id:'fridge',   cat:'kitchen',  name:'冷蔵庫',        icon:'fa-snowflake',       w:0.59,d:0.633,h:1.687,colorIdx:10, build:buildFridge,         product:PRODUCT.fridge },
  { id:'toilet',   cat:'sanitary', name:'トイレ',        icon:'fa-toilet',          w:0.418,d:0.76,h:0.817,colorIdx:10, build:buildToilet,         product:PRODUCT.toilet },
  { id:'handbasin',cat:'sanitary', name:'手洗い器',      icon:'fa-faucet',          w:0.46,d:0.205,h:0.85, colorIdx:10, build:buildHandBasin,      product:PRODUCT.handbasin },
  { id:'vanity',   cat:'sanitary', name:'洗面台',        icon:'fa-pump-soap',       w:0.75,d:0.5,  h:1.8,  colorIdx:1,  build:buildVanity,         product:PRODUCT.vanity },
  { id:'washer',   cat:'sanitary', name:'洗濯機',        icon:'fa-soap',            w:0.564,d:0.573,h:1.022,colorIdx:10,build:buildWasher,         product:PRODUCT.washer },
  { id:'bathtub',  cat:'sanitary', name:'浴槽',          icon:'fa-bath',            w:0.82,d:1.64, h:0.465,colorIdx:4,  build:buildBathtub,        product:PRODUCT.bathtub },
  { id:'bathset',  cat:'sanitary', name:'ユニットバス',  icon:'fa-shower',          w:1.6, d:1.6,  h:2.05, colorIdx:10, build:buildBathSet,        product:PRODUCT.bathset },
  { id:'walltv',   cat:'deco',     name:'壁掛けテレビ',  icon:'fa-tv',              w:1.226,d:0.08,h:0.711,colorIdx:13, build:buildWallTV, wallMount:true, product:PRODUCT.walltv },
  { id:'wallac',   cat:'household', name:'壁掛けエアコン',   icon:'fa-wind',         w:0.798,d:0.255,h:0.25,colorIdx:10, build:buildWallAC, wallMount:true, product:PRODUCT.wallac },
  // ---- office ----
  { id:'conftable',  cat:'office',  name:'会議テーブル',      icon:'fa-table',             w:3.6, d:1.2,  h:0.74, colorIdx:8,  build:buildConferenceTable },
  { id:'whiteboard', cat:'office',  name:'ホワイトボード',    icon:'fa-chalkboard',        w:1.5, d:0.04, h:1.4,  colorIdx:1,  build:buildWhiteboard, wallMount:true },
  { id:'projector',cat:'office',  name:'プロジェクター',    icon:'fa-video',        w:0.3, d:0.25, h:0.12, colorIdx:2,  build:buildProjector,         stack:true },
  { id:'projscreen',cat:'office', name:'プロジェクタースクリーン',icon:'fa-rectangle-xmark', w:1.8, d:0.05, h:1.4, colorIdx:1, build:buildProjectorScreen, wallMount:true },
  { id:'filingcab',  cat:'office',  name:'ファイリングキャビネット', icon:'fa-folder',     w:0.46,d:0.62, h:1.32, colorIdx:10, build:buildFilingCabinet },
  { id:'copier',   cat:'office',  name:'コピー機',          icon:'fa-print',        w:0.62,d:0.56, h:1.08, colorIdx:10, build:buildCopier },
  { id:'reception',  cat:'office',  name:'受付カウンター',    icon:'fa-concierge-bell',    w:2.4, d:0.7,  h:1.1,  colorIdx:1,  build:buildReceptionCounter },
  { id:'deskrun',    cat:'office',  name:'連続デスク',        icon:'fa-table-columns',     w:1.2, d:0.7,  h:0.73, colorIdx:1,  build:buildBenchDesk },
  { id:'benchdesk2', cat:'office',  name:'フリーアドレス島',  icon:'fa-table-cells',       w:1.6, d:1.5,  h:0.73, colorIdx:1,  build:buildBenchDeskDouble },
  // ===== 実物家具 (メーカー公式寸法。product: 採用寸法[mm]と出典) =====
  { id:'fagelfjallet_bed', cat:'product', name:'IKEA FÅGELFJÄLLET ベッド（セミダブル）', icon:'fa-bed',   w:1.32,  d:2.07,  h:1.01,  colorIdx:4,  build:buildFagelfjalletBed,
    product:{ brand:'IKEA', model:'FÅGELFJÄLLET 296.309.18（120×200cm・収納ボックス2個付き・ブラックオーク調）', name:'FÅGELFJÄLLET ベッドフレーム セミダブル',
      mm:{ w:1320, d:2070, h:1010 }, checked:'2026-09-19',
      note:'外形 長さ207×幅132cm、ヘッドボード高101cm／フットボード高39cm、ベッド下の空き20cm、マットレスサイズ120×200cm。奥行(D)はヘッドボード〜フットボードの長さ。',
      sources:[ { label:'IKEA公式（日本）商品ページ', url:'https://www.ikea.com/jp/ja/p/fagelfjaellet-bed-frame-with-2-storage-boxes-black-oak-effect-s29630918/' },
                { label:'IKEA公式（スウェーデン）120×200 寸法表', url:'https://www.ikea.com/se/sv/p/fagelfjaellet-saengstomme-off-white-80621053/' } ] } },
  { id:'valnas_sofa2',     cat:'product', name:'IKEA VALNÄS 2人掛けソファ',            icon:'fa-couch', w:2.06,  d:0.94,  h:0.90,  colorIdx:11, build:buildValnasSofa2,
    product:{ brand:'IKEA', model:'VALNÄS 2人掛けソファ 696.153.22（Knäbäck ライトベージュ 等）', name:'VALNÄS 2人掛けソファ',
      mm:{ w:2060, d:940, h:900 }, checked:'2026-09-19',
      note:'幅206×奥行94×高さ90cm。座面高49／座面幅160／座面奥行72／アームレスト高55cm。日本サイトの型番は要確認（寸法は英国公式ページで確認）。',
      sources:[ { label:'IKEA公式（UK）VALNÄS 2-seat sofa', url:'https://www.ikea.com/gb/en/p/valnaes-2-seat-sofa-knaebaeck-light-beige-s69615322/' },
                { label:'IKEA公式（日本）VALNÄSシリーズ', url:'https://www.ikea.com/jp/ja/cat/valnaes-covers-700827/' } ] } },
  { id:'ugglerum_ct',      cat:'product', name:'IKEA UGGLERUM コーヒーテーブル',        icon:'fa-table', w:1.30,  d:0.65,  h:0.43,  colorIdx:8,  build:buildUgglerumCoffeeTable,
    product:{ brand:'IKEA', model:'UGGLERUM 606.279.80（ウォールナット材突き板 130×65cm）', name:'UGGLERUM コーヒーテーブル',
      mm:{ w:1300, d:650, h:430 }, checked:'2026-09-19',
      note:'長さ130×幅65×高さ43cm、最大荷重20kg。日本での取扱いは要確認（寸法は英国／米国公式ページで確認）。',
      sources:[ { label:'IKEA公式（UK）UGGLERUM coffee table', url:'https://www.ikea.com/gb/en/p/ugglerum-coffee-table-walnut-veneer-60627980/' },
                { label:'IKEA公式（US）UGGLERUM coffee table', url:'https://www.ikea.com/us/en/p/ugglerum-coffee-table-walnut-veneer-60627980/' } ] } },
  { id:'fjallbo_tv',       cat:'product', name:'IKEA FJÄLLBO テレビ台 150',            icon:'fa-tv',    w:1.50,  d:0.36,  h:0.54,  colorIdx:8,  build:buildFjallboTvBench,
    product:{ brand:'IKEA', model:'FJÄLLBO 303.392.93（ブラック 150×36×54cm）', name:'FJÄLLBO テレビ台',
      mm:{ w:1500, d:360, h:540 }, checked:'2026-09-19',
      note:'幅150×奥行36×高さ54cm。100cm幅（705.013.10）もあるが、55V型テレビ（幅122.6cm）を載せるため150cm幅を採用。背板なし。',
      sources:[ { label:'IKEA公式（日本）FJÄLLBO テレビ台 150x36x54', url:'https://www.ikea.com/jp/ja/p/fjaellbo-tv-bench-black-30339293/' },
                { label:'IKEA公式（日本）FJÄLLBO テレビ台 100x36x54', url:'https://www.ikea.com/jp/ja/p/fjaellbo-tv-bench-black-70501310/' } ] } },
  { id:'regza55e770s',     cat:'product', name:'レグザ 55E770S（55V型テレビ）',         icon:'fa-tv',    w:1.226, d:0.287, h:0.761, colorIdx:13, build:buildRegza55E770S, stack:true,
    product:{ brand:'TVS REGZA', model:'55E770S（E7 series・4K Mini LED液晶）', name:'レグザ 55E770S',
      mm:{ w:1226, d:287, h:761 }, weightKg:16.0, checked:'2026-09-19',
      note:'スタンド含む外形寸法 幅122.6×高さ76.1×奥行28.7cm、質量16.0kg。テレビ台に載せて使用（テレビ台の奥行36cm ≧ スタンド奥行28.7cm）。',
      sources:[ { label:'REGZA公式 仕様表（E770S）', url:'https://www.regza.com/tv/lineup/e770s/spec' },
                { label:'REGZA公式 商品トップ（E770S）', url:'https://www.regza.com/tv/lineup/e770s' },
                { label:'参考: ヨドバシ.com 55E770S', url:'https://www.yodobashi.com/product/100000001009940323/' } ] } },
  { id:'gondola',    cat:'shop',    name:'ゴンドラ什器(両面)',icon:'fa-shelves',           w:1.2, d:0.6,  h:1.5,  colorIdx:1,  build:buildGondolaShelf },
  // ---- museum ----
  { id:'displaycase',cat:'museum',  name:'展示ケース',        icon:'fa-box-open',          w:0.88,d:0.52, h:1.3,  colorIdx:10, build:buildDisplayCase },
  { id:'pedestal',   cat:'museum',  name:'展示台',            icon:'fa-chess-rook',        w:0.5, d:0.5,  h:1.05, colorIdx:1,  build:buildPedestal },
  { id:'infopanel',  cat:'museum',  name:'解説パネル',        icon:'fa-sign-hanging',      w:0.76,d:0.03, h:1.5,  colorIdx:1,  build:buildInfoPanel },
  // ---- shop ----
  { id:'shelfrack',  cat:'shop',    name:'商品棚',            icon:'fa-shelves',           w:1.2, d:0.5,  h:1.9,  colorIdx:1,  build:buildShelfRack },
  { id:'register',   cat:'shop',    name:'レジカウンター',    icon:'fa-cash-register',     w:1.2, d:0.65, h:0.9,  colorIdx:1,  build:buildRegisterCounter },
  { id:'showcasefridge', cat:'shop',name:'ショーケース冷蔵庫',icon:'fa-temperature-low',   w:1.2, d:0.72, h:2.0,  colorIdx:10, build:buildShowcaseFridge },
  { id:'barcounter', cat:'shop',    name:'バーカウンター',    icon:'fa-martini-glass',     w:2.4, d:0.5,  h:1.1,  colorIdx:8,  build:buildBarCounter },
  { id:'barstool',   cat:'shop',    name:'バースツール',      icon:'fa-chair',             w:0.4, d:0.4,  h:0.85, colorIdx:2,  build:buildBarStool },
  { id:'roundtable', cat:'shop',    name:'丸テーブル',        icon:'fa-circle',            w:0.9, d:0.9,  h:0.74, colorIdx:8,  build:buildRoundTable },
  // ---- seating variants ----
  { id:'sofa2',      cat:'seating', name:'2人掛けソファ',     icon:'fa-couch',             w:1.9, d:0.95, h:0.83, colorIdx:11, build:(o)=>buildSofa3({...o,seats:2}), product:PRODUCT.sofa2 },
  { id:'sofalow',    cat:'seating', name:'ローソファ',         icon:'fa-couch',             w:2.2, d:1.0,  h:0.72, colorIdx:0,  build:(o)=>buildSofa3({...o,low:true}) },
  { id:'sofal',      cat:'seating', name:'Lソファ',            icon:'fa-couch',             w:2.8, d:1.63, h:0.83, colorIdx:11, build:buildSofaL,       product:PRODUCT.sofal },
  { id:'stool',      cat:'seating', name:'スツール',           icon:'fa-chair',             w:0.4, d:0.4,  h:0.46, colorIdx:2,  build:buildStool },
  { id:'bench',      cat:'seating', name:'ベンチ',             icon:'fa-minus',             w:1.4, d:0.4,  h:0.45, colorIdx:8,  build:buildBench },
  { id:'loungechair',cat:'seating', name:'ラウンジチェア',    icon:'fa-chair',             w:0.8, d:0.85, h:0.78, colorIdx:0,  build:buildLoungeChair },
  { id:'ottoman',    cat:'seating', name:'オットマン',         icon:'fa-cube',              w:0.6, d:0.6,  h:0.4,  colorIdx:5,  build:buildOttoman },
  // ---- table variants ----
  { id:'consoletab', cat:'table',   name:'コンソールテーブル',icon:'fa-table',             w:1.1, d:0.32, h:0.8,  colorIdx:8,  build:buildConsoleTable },
  { id:'roundctab',  cat:'table',   name:'丸コーヒーテーブル',icon:'fa-circle',            w:0.8, d:0.8,  h:0.42, colorIdx:0,  build:buildRoundCoffeeTable },
  { id:'cafechr',       cat:'seating', name:'カフェチェア',          icon:'fa-chair',    w:0.46, d:0.48, h:0.87, colorIdx:8,  build:buildCafeChair },
  { id:'windsorchair',  cat:'seating', name:'ウィンザーチェア',      icon:'fa-chair',    w:0.48, d:0.48, h:0.95, colorIdx:8,  build:buildWindsorChair },
  { id:'stackchr',      cat:'seating', name:'スタッキングチェア',    icon:'fa-chair',    w:0.46, d:0.5,  h:0.82, colorIdx:10, build:buildStackingChair },
  { id:'upholchr',      cat:'seating', name:'レストランチェア',      icon:'fa-chair',    w:0.52, d:0.54, h:0.92, colorIdx:0,  build:buildUpholsteredChair },
  { id:'cafetable',     cat:'table',   name:'カフェテーブル',        icon:'fa-table',    w:0.65, d:0.65, h:0.74, colorIdx:8,  build:buildCafeTable },
  { id:'roundtablesm',  cat:'table',   name:'丸テーブル小',          icon:'fa-circle',   w:0.7,  d:0.7,  h:0.74, colorIdx:8,  build:buildRoundTableSm },
  // ---- sleep variants ----
  { id:'bunkbed',    cat:'sleep',   name:'二段ベッド',         icon:'fa-bed',               w:0.97,d:2.06, h:1.57, colorIdx:0,  build:buildBunkBed,     product:PRODUCT.bunkbed },
  // ---- deco variants ----
  { id:'pendlamp',   cat:'deco',    name:'ペンダントライト',  icon:'fa-lightbulb',         w:0.45,d:0.45, h:1.2,  colorIdx:1,  build:buildPendantLamp, product:PRODUCT.pendlamp },
  { id:'desklamp',   cat:'deco',    name:'デスクランプ',       icon:'fa-lightbulb',         w:0.3, d:0.3,  h:0.5,  colorIdx:2,  build:buildDeskLamp,   stack:true },
  { id:'tablelamp',  cat:'deco',    name:'テーブルランプ',    icon:'fa-lightbulb',         w:0.3, d:0.3,  h:0.55, colorIdx:6,  build:buildTableLamp,  stack:true },
  { id:'cactus',      cat:'deco',    name:'サボテン',           icon:'fa-leaf',     w:0.30, d:0.30, h:0.55,  colorIdx:5,  build:buildCactus,        stack:true },
  { id:'succulent',   cat:'deco',    name:'多肉植物',           icon:'fa-leaf',     w:0.25, d:0.25, h:0.20,  colorIdx:5,  build:buildSucculent,     stack:true },
  // 観葉植物シリーズ
  { id:'monstera',    cat:'deco',    name:'モンステラ',         icon:'fa-leaf',     w:0.80, d:0.80, h:1.65,  colorIdx:5,  build:buildMonstera },
  { id:'dracaena',    cat:'deco',    name:'ドラセナ',           icon:'fa-leaf',     w:0.50, d:0.50, h:1.30,  colorIdx:5,  build:buildDracaena },
  { id:'sansevieria', cat:'deco',    name:'サンスベリア',       icon:'fa-leaf',     w:0.45, d:0.45, h:0.85,  colorIdx:5,  build:buildSansevieria },
  { id:'ficus_umb',   cat:'deco',    name:'フィカス・ウンベラータ',icon:'fa-leaf',  w:0.80, d:0.80, h:1.80,  colorIdx:5,  build:buildFicusUmbellata },
  { id:'rhapis',      cat:'deco',    name:'シュロチク',         icon:'fa-leaf',     w:0.70, d:0.70, h:1.40,  colorIdx:5,  build:buildRhapis },
  { id:'pothos',      cat:'deco',    name:'ポトス',             icon:'fa-leaf',     w:0.40, d:0.40, h:0.35,  colorIdx:5,  build:buildPothos,        stack:true },
  { id:'bamboo',      cat:'deco',    name:'バンブー',           icon:'fa-leaf',     w:0.35, d:0.35, h:0.85,  colorIdx:5,  build:buildBamboo,        stack:true },
  { id:'strelitzia',  cat:'deco',    name:'ストレリチア',       icon:'fa-leaf',     w:0.75, d:0.75, h:1.60,  colorIdx:5,  build:buildStrelitzia },
  { id:'benjamin',    cat:'deco',    name:'ベンジャミン',       icon:'fa-leaf',     w:0.70, d:0.70, h:1.55,  colorIdx:5,  build:buildBenjamin },
  { id:'olive',       cat:'deco',    name:'オリーブ',           icon:'fa-leaf',     w:0.60, d:0.60, h:1.10,  colorIdx:5,  build:buildOlive },
  { id:'zzplant',     cat:'deco',    name:'ZZプラント',         icon:'fa-leaf',     w:0.55, d:0.55, h:1.05,  colorIdx:5,  build:buildZZPlant },
  { id:'roundrug',   cat:'deco',    name:'丸ラグ',             icon:'fa-circle',            w:1.6, d:1.6,  h:0.02, colorIdx:3,  build:buildRoundRug },
  { id:'wallart',    cat:'deco',    name:'ウォールアート',    icon:'fa-image',             w:0.8, d:0.04, h:0.6,  colorIdx:9,  build:buildWallArt,    wallMount:true },
  { id:'wallclock',  cat:'deco',    name:'壁掛け時計',         icon:'fa-clock',             w:0.4, d:0.06, h:0.4,  colorIdx:2,  build:buildWallClock,  wallMount:true },
  // ---- storage variant ----
  { id:'glasscab',   cat:'storage', name:'ガラス棚',           icon:'fa-wine-glass',        w:0.9, d:0.4,  h:1.8,  colorIdx:1,  build:buildGlassCabinet },
  // ---- lab (実験 / 試験 / 加工) ----
  { id:'labbench',   cat:'lab',     name:'実験台',            icon:'fa-flask-vial',        w:2.0,  d:0.75, h:0.85, colorIdx:1,  build:buildLabBench },
  { id:'fumehood',   cat:'lab',     name:'ドラフトチャンバー',icon:'fa-wind',              w:1.4,  d:0.8,  h:2.3,  colorIdx:10, build:buildFumeHood },
  { id:'microscope', cat:'lab',     name:'顕微鏡',            icon:'fa-microscope',        w:0.3,  d:0.4,  h:0.45, colorIdx:2,  build:buildMicroscope, stack:true },
  { id:'centrifuge', cat:'lab',     name:'遠心分離機',        icon:'fa-fan',               w:0.55, d:0.55, h:0.4,  colorIdx:10, build:buildCentrifuge, stack:true },
  { id:'analbalance',cat:'lab',     name:'電子天秤',          icon:'fa-scale-balanced',    w:0.3,  d:0.4,  h:0.32, colorIdx:10, build:buildAnalyticalBalance, stack:true },
  { id:'chemshelf',  cat:'lab',     name:'薬品棚',            icon:'fa-bottle-droplet',    w:1.0,  d:0.4,  h:1.9,  colorIdx:1,  build:buildChemShelf },
  { id:'glassware',  cat:'lab',     name:'実験ガラス器具',    icon:'fa-vial',              w:0.4,  d:0.3,  h:0.32, colorIdx:5,  build:buildGlassware, stack:true },
  { id:'oscilloscope',cat:'lab',    name:'オシロスコープ',    icon:'fa-wave-square',       w:0.42, d:0.4,  h:0.3,  colorIdx:2,  build:buildOscilloscope, stack:true },
  { id:'testbench',  cat:'lab',     name:'測定試験機',        icon:'fa-gauge-high',        w:0.9,  d:0.7,  h:1.6,  colorIdx:2,  build:buildTestBench },
  { id:'lathe',      cat:'lab',     name:'旋盤',              icon:'fa-gears',             w:1.8,  d:0.8,  h:1.35, colorIdx:6,  build:buildLathe },
  { id:'milling',    cat:'lab',     name:'フライス盤',        icon:'fa-screwdriver-wrench',w:1.2,  d:1.1,  h:1.95, colorIdx:6,  build:buildMillingMachine },
  { id:'drillpress', cat:'lab',     name:'ボール盤',          icon:'fa-arrow-down-long',   w:0.6,  d:0.7,  h:1.75, colorIdx:6,  build:buildDrillPress },
  { id:'grinder',    cat:'lab',     name:'グラインダー',      icon:'fa-circle-notch',      w:0.7,  d:0.45, h:1.25, colorIdx:6,  build:buildBenchGrinder },
  { id:'toolrack',   cat:'lab',     name:'工具ラック',        icon:'fa-toolbox',           w:1.0,  d:0.12, h:1.2,  colorIdx:2,  build:buildToolRack, wallMount:true },
  // ---- machining equipment ----
  { id:'bandsaw',    cat:'lab',     name:'帯鋸盤',            icon:'fa-saw',               w:0.6,  d:0.55, h:1.55, colorIdx:6,  build:buildBandSaw },
  { id:'welder',     cat:'lab',     name:'溶接機',            icon:'fa-bolt',              w:0.55, d:0.45, h:0.9,  colorIdx:6,  build:buildWelderStation },
  { id:'hydpress',   cat:'lab',     name:'プレス機',          icon:'fa-arrow-down',        w:0.7,  d:0.65, h:1.8,  colorIdx:6,  build:buildHydraulicPress },
  { id:'printer3d',  cat:'lab',     name:'3Dプリンター',      icon:'fa-cube',              w:0.5,  d:0.5,  h:0.6,  colorIdx:10, build:build3DPrinter,   stack:true },
  { id:'lasercutter',cat:'lab',     name:'レーザーカッター',  icon:'fa-laser-pointer',     w:1.0,  d:0.7,  h:0.35, colorIdx:2,  build:buildLaserCutter },
  { id:'scrollsaw',  cat:'lab',     name:'糸鋸盤',            icon:'fa-scissors',          w:0.55, d:0.45, h:0.95, colorIdx:6,  build:buildScrollSaw },
  // ---- analytical instruments ----
  { id:'hplc',       cat:'lab',     name:'HPLCクロマトグラフ',icon:'fa-chart-line',        w:0.5,  d:0.55, h:1.6,  colorIdx:10, build:buildHPLC },
  { id:'spectropho', cat:'lab',     name:'分光光度計',        icon:'fa-radiation',         w:0.55, d:0.4,  h:0.35, colorIdx:10, build:buildSpectrophotometer, stack:true },
  { id:'laboven',    cat:'lab',     name:'乾燥オーブン',      icon:'fa-fire',              w:0.6,  d:0.5,  h:0.6,  colorIdx:2,  build:buildLabOven },
  { id:'incubator',  cat:'lab',     name:'インキュベーター',  icon:'fa-temperature-half',  w:0.7,  d:0.65, h:0.85, colorIdx:10, build:buildIncubator },
  { id:'ultrasonic', cat:'lab',     name:'超音波洗浄機',      icon:'fa-water',             w:0.35, d:0.28, h:0.28, colorIdx:10, build:buildUltrasonicCleaner, stack:true },
  { id:'vacpump',    cat:'lab',     name:'真空ポンプ',        icon:'fa-pump-soap',         w:0.4,  d:0.3,  h:0.4,  colorIdx:6,  build:buildVacuumPump,  stack:true },
  // ---- factory heavy equipment ----
  { id:'forklift',   cat:'factory', name:'フォークリフト',   icon:'fa-truck-moving',      w:1.45, d:4.0,  h:2.25, colorIdx:12, build:buildForklift },
  { id:'alumcoil',   cat:'factory', name:'アルミコイル',     icon:'fa-circle',            w:1.0,  d:0.8,  h:0.8,  colorIdx:10, build:buildAluminumCoil },
  { id:'scrpbucket', cat:'factory', name:'屑バケット',       icon:'fa-trash',             w:1.0,  d:1.0,  h:0.7,  colorIdx:13, build:buildScrapBucket },
  { id:'tensile',    cat:'lab',     name:'引張試験機',       icon:'fa-arrows-up-down',    w:0.8,  d:0.7,  h:2.0,  colorIdx:10, build:buildTensileTestMachine },
  { id:'woodpallet', cat:'factory', name:'木製パレット',     icon:'fa-pallet',             w:1.1,  d:1.1,  h:0.145, colorIdx:0,  build:buildWoodPallet },
  { id:'steelpallet',cat:'factory', name:'鉄パレット',       icon:'fa-pallet',             w:1.1,  d:1.1,  h:0.15, colorIdx:6,  build:buildSteelPallet },
  { id:'resinpallet',cat:'factory', name:'樹脂パレット',     icon:'fa-pallet',             w:1.1,  d:1.1,  h:0.15, colorIdx:9,  build:buildResinPallet },
  { id:'drum',           cat:'factory', name:'ドラム缶',           icon:'fa-circle',              w:0.58, d:0.58, h:0.88,  colorIdx:9,  build:buildDrum },
  // ---- 大型工業機械 ----
  { id:'cnc_center',     cat:'factory', name:'CNCマシニングセンタ', icon:'fa-gear',                w:3.0,  d:2.2,  h:2.8,   colorIdx:10, build:buildCNCMachiningCenter },
  { id:'ind_robot',      cat:'factory', name:'大型産業ロボット',    icon:'fa-robot',               w:1.2,  d:1.2,  h:2.4,   colorIdx:10, build:buildIndustrialRobotLg },
  { id:'lg_hydpress',    cat:'factory', name:'大型油圧プレス',      icon:'fa-compress-arrows-alt', w:3.2,  d:2.6,  h:5.5,   colorIdx:11, build:buildLargeHydraulicPress },
  { id:'ind_furnace',    cat:'factory', name:'工業炉',              icon:'fa-fire',                w:2.0,  d:1.5,  h:2.2,   colorIdx:2,  build:buildIndustrialFurnace },
  { id:'inj_molder',     cat:'factory', name:'射出成形機',          icon:'fa-cubes',               w:3.5,  d:1.5,  h:2.2,   colorIdx:10, build:buildInjectionMolder },
  // ---- 新規アイテム ----
  { id:'jib_crane',      cat:'factory', name:'ジブクレーン',        icon:'fa-arrow-up-from-bracket', w:2.2,  d:0.5,  h:4.2,   colorIdx:7,  build:buildJibCrane },
  { id:'fire_ext',       cat:'factory', name:'消火器',              icon:'fa-fire-extinguisher',     w:0.2,  d:0.2,  h:0.65,  colorIdx:3,  build:buildFireExtinguisher, stack:true },
  { id:'alumcoil_banded',cat:'factory', name:'バンド掛けアルミコイル',icon:'fa-circle',              w:1.0,  d:0.8,  h:0.8,   colorIdx:10, build:buildBandedAlumCoil },
  { id:'alumcoil_packed', cat:'factory',name:'梱包済みアルミコイル', icon:'fa-box-archive',          w:1.0,  d:0.8,  h:0.8,   colorIdx:1,  build:buildPackagedAlumCoil },
  { id:'alumcoil_export', cat:'factory',name:'輸出梱包アルミコイル', icon:'fa-pallet',               w:1.2,  d:1.2,  h:1.0,   colorIdx:8,  build:buildExportAlumCoil },
  { id:'alumcoil_side',  cat:'factory', name:'横倒しアルミコイル',   icon:'fa-circle',               w:0.8,  d:1.0,  h:0.8,   colorIdx:10, build:buildAlumCoilSide },
  { id:'worker',         cat:'factory', name:'作業員',              icon:'fa-person-walking',        w:0.5,  d:0.5,  h:1.8,   colorIdx:20, build:buildWorker },
  // ---- 家具追加 ----
  { id:'monitor',       cat:'office',   name:'PCモニター',          icon:'fa-desktop',        w:0.52, d:0.18, h:0.44, colorIdx:2,  build:buildMonitor,         stack:true },
  { id:'kotatsu',       cat:'table',    name:'こたつ',              icon:'fa-table',          w:0.75, d:0.75, h:0.38, colorIdx:0,  build:buildKotatsu,    product:PRODUCT.kotatsu },
  { id:'dresser',       cat:'storage',  name:'ドレッサー',          icon:'fa-mirror',         w:1.0,  d:0.5,  h:1.59, colorIdx:1,  build:buildDresser,    product:PRODUCT.dresser },
  { id:'hangerrack',    cat:'storage',  name:'ハンガーラック',      icon:'fa-shirt',          w:0.99, d:0.46, h:1.51, colorIdx:10, build:buildHangerRack, product:PRODUCT.hangerrack },
  { id:'piano',         cat:'deco',     name:'アップライトピアノ',  icon:'fa-music',          w:1.45, d:0.6,  h:1.22, colorIdx:2,  build:buildPiano },
  { id:'espresso',      cat:'kitchen',  name:'エスプレッソマシン',  icon:'fa-mug-hot',        w:0.3,  d:0.38, h:0.42, colorIdx:7,  build:buildEspressoMachine, stack:true },
  { id:'dishwasher',    cat:'kitchen',  name:'食洗機',              icon:'fa-soap',           w:0.6,  d:0.6,  h:0.85, colorIdx:10, build:buildDishwasher },
  { id:'locker',        cat:'storage',  name:'ロッカー',            icon:'fa-lock',           w:1.2,  d:0.45, h:1.85, colorIdx:6,  build:buildLockerUnit },
  { id:'vendingmachine',cat:'shop',     name:'自動販売機',          icon:'fa-coins',          w:0.75, d:0.35, h:1.85, colorIdx:3,  build:buildVendingMachine },
  { id:'atm',           cat:'shop',     name:'ATM',                 icon:'fa-landmark',       w:0.65, d:0.55, h:1.7,  colorIdx:2,  build:buildATM },
  // ---- 学校 ----
  { id:'schooldesk',  cat:'school',   name:'学習机',              icon:'fa-pen-ruler',      w:0.65, d:0.45, h:0.72, colorIdx:0,  build:buildSchoolDesk },
  { id:'blackboard',  cat:'school',   name:'黒板',                icon:'fa-chalkboard',     w:3.0,  d:0.06, h:1.2,  colorIdx:14, build:buildBlackboard, wallMount:true },
  // ---- 和室 ----
  { id:'zabuton',     cat:'seating',  name:'座布団',              icon:'fa-square',         w:0.55, d:0.55, h:0.08, colorIdx:6,  build:buildZabuton },
  // ---- アウトドア ----
  { id:'tent',        cat:'outdoor',  name:'テント',              icon:'fa-tent',           w:2.2,  d:2.4,  h:1.35, colorIdx:5,  build:buildTent },
  { id:'campchair',   cat:'outdoor',  name:'キャンプチェア',      icon:'fa-chair',          w:0.6,  d:0.62, h:0.85, colorIdx:4,  build:buildCampChair },
  { id:'campfire',    cat:'outdoor',  name:'焚き火',              icon:'fa-fire',           w:0.7,  d:0.7,  h:0.45, colorIdx:2,  build:buildCampfire },
  { id:'coolerbox',   cat:'outdoor',  name:'クーラーボックス',    icon:'fa-box-archive',    w:0.6,  d:0.4,  h:0.42, colorIdx:3,  build:buildCoolerBox },
  { id:'lantern',     cat:'outdoor',  name:'ランタン',            icon:'fa-lightbulb',      w:0.18, d:0.18, h:0.32, colorIdx:14, build:buildLantern,   stack:true },
  // ---- キッズ / 人物 ----
  { id:'girl',     cat:'kids', name:'女の子(小学生)',   icon:'fa-child-dress', w:0.5,  d:0.5,  h:1.28, colorIdx:15, build:(o)=>buildPerson({ ...o, h:1.28, style:'twin',  skirt:true, bag:'randoseru', headBig:true, bottom:'#ef7fa6', hair:'#5a3a26', shoe:'#e2607a' }) },
  { id:'boy',      cat:'kids', name:'男の子(小学生)',   icon:'fa-child',       w:0.5,  d:0.5,  h:1.34, colorIdx:19, build:(o)=>buildPerson({ ...o, h:1.34, style:'short', bag:'randoseru', headBig:true, bottom:'#3a4f68', hair:'#2e2017', shoe:'#3a4f68' }) },
  { id:'woman',    cat:'kids', name:'女性',             icon:'fa-person-dress',w:0.5,  d:0.5,  h:1.62, colorIdx:6,  build:(o)=>buildPerson({ ...o, h:1.62, style:'long',  skirt:true, bottom:'#7a5a8a', hair:'#3a2a1f', shoe:'#caa' }) },
  { id:'man',      cat:'kids', name:'男性',             icon:'fa-person',      w:0.5,  d:0.5,  h:1.76, colorIdx:9,  build:(o)=>buildPerson({ ...o, h:1.76, style:'short', bottom:'#37506a', hair:'#241a12', shoe:'#2a2a2a' }) },
  { id:'toddler',  cat:'kids', name:'幼児',             icon:'fa-baby',        w:0.4,  d:0.4,  h:0.88, colorIdx:16, build:(o)=>buildPerson({ ...o, h:0.88, style:'short', headBig:true, bottom:'#ffd382', hair:'#6a4a30', shoe:'#ff9aa2' }) },
  { id:'teddy',    cat:'kids', name:'テディベア',        icon:'fa-paw',          w:0.36, d:0.32, h:0.46, colorIdx:0,  build:buildTeddyBear,      stack:true },
  { id:'bunny',    cat:'kids', name:'うさぎぬいぐるみ',  icon:'fa-paw',          w:0.3,  d:0.3,  h:0.52, colorIdx:1,  build:buildBunnyPlush,     stack:true },
  { id:'unicorn',  cat:'kids', name:'ユニコーン',        icon:'fa-horse-head',   w:0.5,  d:0.26, h:0.6,  colorIdx:17, build:buildUnicornToy,     stack:true },
  { id:'balloon',  cat:'kids', name:'風船',              icon:'fa-circle',       w:0.34, d:0.34, h:1.5,  colorIdx:15, build:buildBalloon },
  { id:'heartcushion', cat:'kids', name:'ハートクッション', icon:'fa-heart',      w:0.5,  d:0.5,  h:0.18, colorIdx:15, build:buildHeartCushion,   stack:true },
  { id:'blocks',   cat:'kids', name:'つみき',            icon:'fa-cubes',        w:0.3,  d:0.3,  h:0.3,  colorIdx:15, build:buildBuildingBlocks, stack:true },
  { id:'toybox',   cat:'kids', name:'おもちゃ箱',        icon:'fa-box-open',     w:0.6,  d:0.42, h:0.4,  colorIdx:19, build:buildToyBox },
  { id:'dollhouse',cat:'kids', name:'ドールハウス',      icon:'fa-house-chimney',w:0.6,  d:0.42, h:0.7,  colorIdx:15, build:buildDollhouse },
  { id:'cake',     cat:'kids', name:'ホールケーキ',      icon:'fa-cake-candles', w:0.32, d:0.32, h:0.27, colorIdx:1,  build:buildCake,           stack:true },
  { id:'cupcake',  cat:'kids', name:'カップケーキ',      icon:'fa-cookie',       w:0.14, d:0.14, h:0.17, colorIdx:15, build:buildCupcake,        stack:true },
  { id:'kidsbed',  cat:'kids', name:'お姫様ベッド',      icon:'fa-bed',          w:1.05, d:1.9,  h:1.72, colorIdx:15, build:buildKidsBed },
  { id:'kidsdesk', cat:'kids', name:'キッズデスク',      icon:'fa-pen-ruler',    w:0.8,  d:0.5,  h:0.56, colorIdx:19, build:buildKidsDesk },
  { id:'kidschair',cat:'kids', name:'キッズチェア',      icon:'fa-chair',        w:0.34, d:0.34, h:0.6,  colorIdx:18, build:buildKidsChair },
  { id:'garland',  cat:'kids', name:'ガーランド',        icon:'fa-ribbon',       w:1.3,  d:0.04, h:0.4,  colorIdx:15, build:buildGarland,  wallMount:true },
  { id:'starwall', cat:'kids', name:'星の壁飾り',        icon:'fa-star',         w:0.6,  d:0.04, h:0.55, colorIdx:18, build:buildStarWall, wallMount:true },
];


export { FURNITURE_DEFS };
